version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "bun"
    directory: "/client-web"
    schedule:
      interval: "weekly"
    groups:
      client-web-linting:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@typescript-eslint/*"
          - "oxlint"
          - "oxfmt"
