//  ______                        _               _  _  _
//  |  _  \                      | |             | |(_)| |
//  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_
//  | | | | / _ \  | '_ \  / _ \ | __|  / _ \ / _` || || __|
//  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_
//  |___/   \___/  |_| |_| \___/  \__|  \___| \__,_||_| \__|
//
// Generated by skir-typescript-gen
// Home: https://github.com/gepheum/skir-typescript-gen
//
// To install the Skir client library:
//   npm i skir-client

import * as $ from "skir-client";

// -----------------------------------------------------------------------------
// struct UpsertInventoryRuleRequest
// -----------------------------------------------------------------------------

/** Deeply immutable. If you need mutability, use `UpsertInventoryRuleRequest.Mutable`. */
export declare class UpsertInventoryRuleRequest extends $._FrozenBase {
  /**
   * Creates a new instance of `UpsertInventoryRuleRequest`.
   *
   * You must specify all the fields unless you use `create<"partial">({...})>`,
   * in which case missing fields are set to their default values.
   */
  static create<_Wholeness extends "whole" | "partial" = "whole">(
    initializer: UpsertInventoryRuleRequest.Initializer<_Wholeness>
  ): UpsertInventoryRuleRequest;

  private constructor();

  readonly id: string;
  readonly locationName: string;
  readonly expression: string;

  /** Returns this instance (no-op). */
  toFrozen(): this;

  /** Returns a mutable shallow copy of this instance. */
  toMutable(): UpsertInventoryRuleRequest.Mutable;

  /** Default instance with all fields set to their default values. */
  static readonly DEFAULT: UpsertInventoryRuleRequest;

  /** Serializer for `UpsertInventoryRuleRequest` instances. */
  static readonly serializer: $.Serializer<UpsertInventoryRuleRequest>;

  /** Mutable version of this class. */
  static readonly Mutable: typeof UpsertInventoryRuleRequest_Mutable;

  readonly [$._INITIALIZER]: UpsertInventoryRuleRequest.Initializer | undefined;
  private readonly FROZEN: undefined;
}

/**
 * Mutable version of `UpsertInventoryRuleRequest`.
 *
 * @alias UpsertInventoryRuleRequest.Mutable
 */
declare class UpsertInventoryRuleRequest_Mutable {
  /**
   * Creates a new mutable instance.
   *
   * Fields not specified in `initializer` will be set to their default values.
   */
  constructor(initializer?: UpsertInventoryRuleRequest.Initializer<"partial">);

  id: string;
  locationName: string;
  expression: string;

  /** Returns a deeply-immutable copy of this instance. */
  toFrozen(): UpsertInventoryRuleRequest;

  readonly [$._INITIALIZER]: UpsertInventoryRuleRequest.Initializer | undefined;
}

export declare namespace UpsertInventoryRuleRequest {
  interface _Initializer<_Wholeness extends "whole" | "partial"> {
    readonly id: string;
    readonly locationName: string;
    readonly expression: string;
  }

  export type Initializer<_Wholeness extends "whole" | "partial" = "whole"> =
    _Wholeness extends "whole" ? _Initializer<"whole"> : Partial<_Initializer<"partial">>;

  /** Mutable version of UpsertInventoryRuleRequest. */
  export type Mutable = UpsertInventoryRuleRequest_Mutable;
  export type OrMutable = UpsertInventoryRuleRequest | Mutable;
}

// -----------------------------------------------------------------------------
// enum UpsertInventoryRuleResponse
// -----------------------------------------------------------------------------

/** Deeply immutable. */
export declare class UpsertInventoryRuleResponse extends $._EnumBase {
  /**
   * Constant indicating an unknown `UpsertInventoryRuleResponse` (kind: '?').
   *
   * Default value for fields of type `UpsertInventoryRuleResponse`.
   */
  static readonly UNKNOWN:  UpsertInventoryRuleResponse;
  static readonly SUCCESS:  UpsertInventoryRuleResponse;
  static readonly ERROR:  UpsertInventoryRuleResponse;

  /** Gets or creates a `UpsertInventoryRuleResponse` instance from the given initializer. */
  static create<_Wholeness extends "whole" | "partial" = "whole">(
    initializer: UpsertInventoryRuleResponse.Initializer<_Wholeness>
  ): UpsertInventoryRuleResponse;

  /**
   * This instance as the union of all the variant types.
   *
   * Use `union.kind` to determine the variant held by this instance.
   */
  declare readonly union: UpsertInventoryRuleResponse.UnionView;

  /** Serializer for `UpsertInventoryRuleResponse` instances. */
  static readonly serializer: $.Serializer<UpsertInventoryRuleResponse>;
}

export declare namespace UpsertInventoryRuleResponse {
  /** Identifies a variant. */
  export type Kind =
    | "UNKNOWN"
    | "SUCCESS"
    | "ERROR";

  export type Initializer<_Wholeness extends "whole" | "partial" = "whole"> =
    | UpsertInventoryRuleResponse
    | "UNKNOWN"
    | "SUCCESS"
    | "ERROR";

  /** View of a `UpsertInventoryRuleResponse` as a union type. */
  export type UnionView =
    | { kind: "UNKNOWN"; value: undefined }
    | { kind: "SUCCESS"; value: undefined }
    | { kind: "ERROR"; value: undefined };
}

// -----------------------------------------------------------------------------
// struct DeleteInventoryRuleRequest
// -----------------------------------------------------------------------------

/** Deeply immutable. If you need mutability, use `DeleteInventoryRuleRequest.Mutable`. */
export declare class DeleteInventoryRuleRequest extends $._FrozenBase {
  /**
   * Creates a new instance of `DeleteInventoryRuleRequest`.
   *
   * You must specify all the fields unless you use `create<"partial">({...})>`,
   * in which case missing fields are set to their default values.
   */
  static create<_Wholeness extends "whole" | "partial" = "whole">(
    initializer: DeleteInventoryRuleRequest.Initializer<_Wholeness>
  ): DeleteInventoryRuleRequest;

  private constructor();

  readonly id: string;

  /** Returns this instance (no-op). */
  toFrozen(): this;

  /** Returns a mutable shallow copy of this instance. */
  toMutable(): DeleteInventoryRuleRequest.Mutable;

  /** Default instance with all fields set to their default values. */
  static readonly DEFAULT: DeleteInventoryRuleRequest;

  /** Serializer for `DeleteInventoryRuleRequest` instances. */
  static readonly serializer: $.Serializer<DeleteInventoryRuleRequest>;

  /** Mutable version of this class. */
  static readonly Mutable: typeof DeleteInventoryRuleRequest_Mutable;

  readonly [$._INITIALIZER]: DeleteInventoryRuleRequest.Initializer | undefined;
  private readonly FROZEN: undefined;
}

/**
 * Mutable version of `DeleteInventoryRuleRequest`.
 *
 * @alias DeleteInventoryRuleRequest.Mutable
 */
declare class DeleteInventoryRuleRequest_Mutable {
  /**
   * Creates a new mutable instance.
   *
   * Fields not specified in `initializer` will be set to their default values.
   */
  constructor(initializer?: DeleteInventoryRuleRequest.Initializer<"partial">);

  id: string;

  /** Returns a deeply-immutable copy of this instance. */
  toFrozen(): DeleteInventoryRuleRequest;

  readonly [$._INITIALIZER]: DeleteInventoryRuleRequest.Initializer | undefined;
}

export declare namespace DeleteInventoryRuleRequest {
  interface _Initializer<_Wholeness extends "whole" | "partial"> {
    readonly id: string;
  }

  export type Initializer<_Wholeness extends "whole" | "partial" = "whole"> =
    _Wholeness extends "whole" ? _Initializer<"whole"> : Partial<_Initializer<"partial">>;

  /** Mutable version of DeleteInventoryRuleRequest. */
  export type Mutable = DeleteInventoryRuleRequest_Mutable;
  export type OrMutable = DeleteInventoryRuleRequest | Mutable;
}

// -----------------------------------------------------------------------------
// enum DeleteInventoryRuleResponse
// -----------------------------------------------------------------------------

/** Deeply immutable. */
export declare class DeleteInventoryRuleResponse extends $._EnumBase {
  /**
   * Constant indicating an unknown `DeleteInventoryRuleResponse` (kind: '?').
   *
   * Default value for fields of type `DeleteInventoryRuleResponse`.
   */
  static readonly UNKNOWN:  DeleteInventoryRuleResponse;
  static readonly SUCCESS:  DeleteInventoryRuleResponse;
  static readonly ERROR:  DeleteInventoryRuleResponse;

  /** Gets or creates a `DeleteInventoryRuleResponse` instance from the given initializer. */
  static create<_Wholeness extends "whole" | "partial" = "whole">(
    initializer: DeleteInventoryRuleResponse.Initializer<_Wholeness>
  ): DeleteInventoryRuleResponse;

  /**
   * This instance as the union of all the variant types.
   *
   * Use `union.kind` to determine the variant held by this instance.
   */
  declare readonly union: DeleteInventoryRuleResponse.UnionView;

  /** Serializer for `DeleteInventoryRuleResponse` instances. */
  static readonly serializer: $.Serializer<DeleteInventoryRuleResponse>;
}

export declare namespace DeleteInventoryRuleResponse {
  /** Identifies a variant. */
  export type Kind =
    | "UNKNOWN"
    | "SUCCESS"
    | "ERROR";

  export type Initializer<_Wholeness extends "whole" | "partial" = "whole"> =
    | DeleteInventoryRuleResponse
    | "UNKNOWN"
    | "SUCCESS"
    | "ERROR";

  /** View of a `DeleteInventoryRuleResponse` as a union type. */
  export type UnionView =
    | { kind: "UNKNOWN"; value: undefined }
    | { kind: "SUCCESS"; value: undefined }
    | { kind: "ERROR"; value: undefined };
}

// -----------------------------------------------------------------------------
// Methods
// -----------------------------------------------------------------------------

export const UpsertInventoryRule: $.Method<UpsertInventoryRuleRequest, UpsertInventoryRuleResponse>;

export const DeleteInventoryRule: $.Method<DeleteInventoryRuleRequest, DeleteInventoryRuleResponse>;
