//  ______                        _               _  _  _
//  |  _  \                      | |             | |(_)| |
//  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_
//  | | | | / _ \  | '_ \  / _ \ | __|  / _ \ / _` || || __|
//  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_
//  |___/   \___/  |_| |_| \___/  \__|  \___| \__,_||_| \__|
//
// Generated by skir-typescript-gen
// Home: https://github.com/gepheum/skir-typescript-gen
//
// To install the Skir client library:
//   npm i skir-client

import * as $ from "skir-client";

// -----------------------------------------------------------------------------
// struct InventoryRule
// -----------------------------------------------------------------------------

/** Deeply immutable. If you need mutability, use `InventoryRule.Mutable`. */
export declare class InventoryRule extends $._FrozenBase {
  /**
   * Creates a new instance of `InventoryRule`.
   *
   * You must specify all the fields unless you use `create<"partial">({...})>`,
   * in which case missing fields are set to their default values.
   */
  static create<_Wholeness extends "whole" | "partial" = "whole">(
    initializer: InventoryRule.Initializer<_Wholeness>
  ): InventoryRule;

  private constructor();

  readonly id: string;
  readonly locationName: string;
  readonly expression: string;

  /** Returns this instance (no-op). */
  toFrozen(): this;

  /** Returns a mutable shallow copy of this instance. */
  toMutable(): InventoryRule.Mutable;

  /** Default instance with all fields set to their default values. */
  static readonly DEFAULT: InventoryRule;

  /** Serializer for `InventoryRule` instances. */
  static readonly serializer: $.Serializer<InventoryRule>;

  /** Mutable version of this class. */
  static readonly Mutable: typeof InventoryRule_Mutable;

  readonly [$._INITIALIZER]: InventoryRule.Initializer | undefined;
  private readonly FROZEN: undefined;
}

/**
 * Mutable version of `InventoryRule`.
 *
 * @alias InventoryRule.Mutable
 */
declare class InventoryRule_Mutable {
  /**
   * Creates a new mutable instance.
   *
   * Fields not specified in `initializer` will be set to their default values.
   */
  constructor(initializer?: InventoryRule.Initializer<"partial">);

  id: string;
  locationName: string;
  expression: string;

  /** Returns a deeply-immutable copy of this instance. */
  toFrozen(): InventoryRule;

  readonly [$._INITIALIZER]: InventoryRule.Initializer | undefined;
}

export declare namespace InventoryRule {
  interface _Initializer<_Wholeness extends "whole" | "partial"> {
    readonly id: string;
    readonly locationName: string;
    readonly expression: string;
  }

  export type Initializer<_Wholeness extends "whole" | "partial" = "whole"> =
    _Wholeness extends "whole" ? _Initializer<"whole"> : Partial<_Initializer<"partial">>;

  /** Mutable version of InventoryRule. */
  export type Mutable = InventoryRule_Mutable;
  export type OrMutable = InventoryRule | Mutable;
}

// -----------------------------------------------------------------------------
// struct InventoryRuleList
// -----------------------------------------------------------------------------

/** Deeply immutable. If you need mutability, use `InventoryRuleList.Mutable`. */
export declare class InventoryRuleList extends $._FrozenBase {
  /**
   * Creates a new instance of `InventoryRuleList`.
   *
   * You must specify all the fields unless you use `create<"partial">({...})>`,
   * in which case missing fields are set to their default values.
   */
  static create<_Wholeness extends "whole" | "partial" = "whole">(
    initializer: InventoryRuleList.Initializer<_Wholeness>
  ): InventoryRuleList;

  private constructor();

  readonly data: ReadonlyArray<InventoryRule>;
  readonly total: number;

  /** Returns this instance (no-op). */
  toFrozen(): this;

  /** Returns a mutable shallow copy of this instance. */
  toMutable(): InventoryRuleList.Mutable;

  /** Default instance with all fields set to their default values. */
  static readonly DEFAULT: InventoryRuleList;

  /** Serializer for `InventoryRuleList` instances. */
  static readonly serializer: $.Serializer<InventoryRuleList>;

  /** Mutable version of this class. */
  static readonly Mutable: typeof InventoryRuleList_Mutable;

  readonly [$._INITIALIZER]: InventoryRuleList.Initializer | undefined;
  private readonly FROZEN: undefined;
}

/**
 * Mutable version of `InventoryRuleList`.
 *
 * @alias InventoryRuleList.Mutable
 */
declare class InventoryRuleList_Mutable {
  /**
   * Creates a new mutable instance.
   *
   * Fields not specified in `initializer` will be set to their default values.
   */
  constructor(initializer?: InventoryRuleList.Initializer<"partial">);

  data: ReadonlyArray<InventoryRule.OrMutable>;
  total: number;

  /**
   * If the value of `data` is already mutable, returns it as-is.
   * Otherwise, makes a mutable copy, assigns it back to `data` and returns it.
   */
  get mutableData(): Array<InventoryRule.OrMutable>;

  /** Returns a deeply-immutable copy of this instance. */
  toFrozen(): InventoryRuleList;

  readonly [$._INITIALIZER]: InventoryRuleList.Initializer | undefined;
}

export declare namespace InventoryRuleList {
  interface _Initializer<_Wholeness extends "whole" | "partial"> {
    readonly data: ReadonlyArray<InventoryRule.Initializer<_Wholeness>>;
    readonly total: number;
  }

  export type Initializer<_Wholeness extends "whole" | "partial" = "whole"> =
    _Wholeness extends "whole" ? _Initializer<"whole"> : Partial<_Initializer<"partial">>;

  /** Mutable version of InventoryRuleList. */
  export type Mutable = InventoryRuleList_Mutable;
  export type OrMutable = InventoryRuleList | Mutable;
}

// -----------------------------------------------------------------------------
// struct ListInventoryRulesRequest
// -----------------------------------------------------------------------------

/** Deeply immutable. If you need mutability, use `ListInventoryRulesRequest.Mutable`. */
export declare class ListInventoryRulesRequest extends $._FrozenBase {
  /**
   * Creates a new instance of `ListInventoryRulesRequest`.
   *
   * You must specify all the fields unless you use `create<"partial">({...})>`,
   * in which case missing fields are set to their default values.
   */
  static create<_Wholeness extends "whole" | "partial" = "whole">(
    initializer: ListInventoryRulesRequest.Initializer<_Wholeness>
  ): ListInventoryRulesRequest;

  private constructor();

  readonly unit: boolean;

  /** Returns this instance (no-op). */
  toFrozen(): this;

  /** Returns a mutable shallow copy of this instance. */
  toMutable(): ListInventoryRulesRequest.Mutable;

  /** Default instance with all fields set to their default values. */
  static readonly DEFAULT: ListInventoryRulesRequest;

  /** Serializer for `ListInventoryRulesRequest` instances. */
  static readonly serializer: $.Serializer<ListInventoryRulesRequest>;

  /** Mutable version of this class. */
  static readonly Mutable: typeof ListInventoryRulesRequest_Mutable;

  readonly [$._INITIALIZER]: ListInventoryRulesRequest.Initializer | undefined;
  private readonly FROZEN: undefined;
}

/**
 * Mutable version of `ListInventoryRulesRequest`.
 *
 * @alias ListInventoryRulesRequest.Mutable
 */
declare class ListInventoryRulesRequest_Mutable {
  /**
   * Creates a new mutable instance.
   *
   * Fields not specified in `initializer` will be set to their default values.
   */
  constructor(initializer?: ListInventoryRulesRequest.Initializer<"partial">);

  unit: boolean;

  /** Returns a deeply-immutable copy of this instance. */
  toFrozen(): ListInventoryRulesRequest;

  readonly [$._INITIALIZER]: ListInventoryRulesRequest.Initializer | undefined;
}

export declare namespace ListInventoryRulesRequest {
  interface _Initializer<_Wholeness extends "whole" | "partial"> {
    readonly unit: boolean;
  }

  export type Initializer<_Wholeness extends "whole" | "partial" = "whole"> =
    _Wholeness extends "whole" ? _Initializer<"whole"> : Partial<_Initializer<"partial">>;

  /** Mutable version of ListInventoryRulesRequest. */
  export type Mutable = ListInventoryRulesRequest_Mutable;
  export type OrMutable = ListInventoryRulesRequest | Mutable;
}

// -----------------------------------------------------------------------------
// struct InventoryProjectionRequest
// -----------------------------------------------------------------------------

/** Deeply immutable. If you need mutability, use `InventoryProjectionRequest.Mutable`. */
export declare class InventoryProjectionRequest extends $._FrozenBase {
  /**
   * Creates a new instance of `InventoryProjectionRequest`.
   *
   * You must specify all the fields unless you use `create<"partial">({...})>`,
   * in which case missing fields are set to their default values.
   */
  static create<_Wholeness extends "whole" | "partial" = "whole">(
    initializer: InventoryProjectionRequest.Initializer<_Wholeness>
  ): InventoryProjectionRequest;

  private constructor();

  readonly sortBy: string;
  readonly groupBy: string;

  /** Returns this instance (no-op). */
  toFrozen(): this;

  /** Returns a mutable shallow copy of this instance. */
  toMutable(): InventoryProjectionRequest.Mutable;

  /** Default instance with all fields set to their default values. */
  static readonly DEFAULT: InventoryProjectionRequest;

  /** Serializer for `InventoryProjectionRequest` instances. */
  static readonly serializer: $.Serializer<InventoryProjectionRequest>;

  /** Mutable version of this class. */
  static readonly Mutable: typeof InventoryProjectionRequest_Mutable;

  readonly [$._INITIALIZER]: InventoryProjectionRequest.Initializer | undefined;
  private readonly FROZEN: undefined;
}

/**
 * Mutable version of `InventoryProjectionRequest`.
 *
 * @alias InventoryProjectionRequest.Mutable
 */
declare class InventoryProjectionRequest_Mutable {
  /**
   * Creates a new mutable instance.
   *
   * Fields not specified in `initializer` will be set to their default values.
   */
  constructor(initializer?: InventoryProjectionRequest.Initializer<"partial">);

  sortBy: string;
  groupBy: string;

  /** Returns a deeply-immutable copy of this instance. */
  toFrozen(): InventoryProjectionRequest;

  readonly [$._INITIALIZER]: InventoryProjectionRequest.Initializer | undefined;
}

export declare namespace InventoryProjectionRequest {
  interface _Initializer<_Wholeness extends "whole" | "partial"> {
    readonly sortBy: string;
    readonly groupBy: string;
  }

  export type Initializer<_Wholeness extends "whole" | "partial" = "whole"> =
    _Wholeness extends "whole" ? _Initializer<"whole"> : Partial<_Initializer<"partial">>;

  /** Mutable version of InventoryProjectionRequest. */
  export type Mutable = InventoryProjectionRequest_Mutable;
  export type OrMutable = InventoryProjectionRequest | Mutable;
}

// -----------------------------------------------------------------------------
// struct InventoryProjectionRow
// -----------------------------------------------------------------------------

/** Deeply immutable. If you need mutability, use `InventoryProjectionRow.Mutable`. */
export declare class InventoryProjectionRow extends $._FrozenBase {
  /**
   * Creates a new instance of `InventoryProjectionRow`.
   *
   * You must specify all the fields unless you use `create<"partial">({...})>`,
   * in which case missing fields are set to their default values.
   */
  static create<_Wholeness extends "whole" | "partial" = "whole">(
    initializer: InventoryProjectionRow.Initializer<_Wholeness>
  ): InventoryProjectionRow;

  private constructor();

  readonly locationName: string;
  readonly cardName: string;
  readonly setCode: string;
  readonly quantity: number;
  readonly groupValue: string;

  /** Returns this instance (no-op). */
  toFrozen(): this;

  /** Returns a mutable shallow copy of this instance. */
  toMutable(): InventoryProjectionRow.Mutable;

  /** Default instance with all fields set to their default values. */
  static readonly DEFAULT: InventoryProjectionRow;

  /** Serializer for `InventoryProjectionRow` instances. */
  static readonly serializer: $.Serializer<InventoryProjectionRow>;

  /** Mutable version of this class. */
  static readonly Mutable: typeof InventoryProjectionRow_Mutable;

  readonly [$._INITIALIZER]: InventoryProjectionRow.Initializer | undefined;
  private readonly FROZEN: undefined;
}

/**
 * Mutable version of `InventoryProjectionRow`.
 *
 * @alias InventoryProjectionRow.Mutable
 */
declare class InventoryProjectionRow_Mutable {
  /**
   * Creates a new mutable instance.
   *
   * Fields not specified in `initializer` will be set to their default values.
   */
  constructor(initializer?: InventoryProjectionRow.Initializer<"partial">);

  locationName: string;
  cardName: string;
  setCode: string;
  quantity: number;
  groupValue: string;

  /** Returns a deeply-immutable copy of this instance. */
  toFrozen(): InventoryProjectionRow;

  readonly [$._INITIALIZER]: InventoryProjectionRow.Initializer | undefined;
}

export declare namespace InventoryProjectionRow {
  interface _Initializer<_Wholeness extends "whole" | "partial"> {
    readonly locationName: string;
    readonly cardName: string;
    readonly setCode: string;
    readonly quantity: number;
    readonly groupValue: string;
  }

  export type Initializer<_Wholeness extends "whole" | "partial" = "whole"> =
    _Wholeness extends "whole" ? _Initializer<"whole"> : Partial<_Initializer<"partial">>;

  /** Mutable version of InventoryProjectionRow. */
  export type Mutable = InventoryProjectionRow_Mutable;
  export type OrMutable = InventoryProjectionRow | Mutable;
}

// -----------------------------------------------------------------------------
// struct InventoryProjection
// -----------------------------------------------------------------------------

/** Deeply immutable. If you need mutability, use `InventoryProjection.Mutable`. */
export declare class InventoryProjection extends $._FrozenBase {
  /**
   * Creates a new instance of `InventoryProjection`.
   *
   * You must specify all the fields unless you use `create<"partial">({...})>`,
   * in which case missing fields are set to their default values.
   */
  static create<_Wholeness extends "whole" | "partial" = "whole">(
    initializer: InventoryProjection.Initializer<_Wholeness>
  ): InventoryProjection;

  private constructor();

  readonly data: ReadonlyArray<InventoryProjectionRow>;
  readonly total: number;

  /** Returns this instance (no-op). */
  toFrozen(): this;

  /** Returns a mutable shallow copy of this instance. */
  toMutable(): InventoryProjection.Mutable;

  /** Default instance with all fields set to their default values. */
  static readonly DEFAULT: InventoryProjection;

  /** Serializer for `InventoryProjection` instances. */
  static readonly serializer: $.Serializer<InventoryProjection>;

  /** Mutable version of this class. */
  static readonly Mutable: typeof InventoryProjection_Mutable;

  readonly [$._INITIALIZER]: InventoryProjection.Initializer | undefined;
  private readonly FROZEN: undefined;
}

/**
 * Mutable version of `InventoryProjection`.
 *
 * @alias InventoryProjection.Mutable
 */
declare class InventoryProjection_Mutable {
  /**
   * Creates a new mutable instance.
   *
   * Fields not specified in `initializer` will be set to their default values.
   */
  constructor(initializer?: InventoryProjection.Initializer<"partial">);

  data: ReadonlyArray<InventoryProjectionRow.OrMutable>;
  total: number;

  /**
   * If the value of `data` is already mutable, returns it as-is.
   * Otherwise, makes a mutable copy, assigns it back to `data` and returns it.
   */
  get mutableData(): Array<InventoryProjectionRow.OrMutable>;

  /** Returns a deeply-immutable copy of this instance. */
  toFrozen(): InventoryProjection;

  readonly [$._INITIALIZER]: InventoryProjection.Initializer | undefined;
}

export declare namespace InventoryProjection {
  interface _Initializer<_Wholeness extends "whole" | "partial"> {
    readonly data: ReadonlyArray<InventoryProjectionRow.Initializer<_Wholeness>>;
    readonly total: number;
  }

  export type Initializer<_Wholeness extends "whole" | "partial" = "whole"> =
    _Wholeness extends "whole" ? _Initializer<"whole"> : Partial<_Initializer<"partial">>;

  /** Mutable version of InventoryProjection. */
  export type Mutable = InventoryProjection_Mutable;
  export type OrMutable = InventoryProjection | Mutable;
}

// -----------------------------------------------------------------------------
// Methods
// -----------------------------------------------------------------------------

export const ListInventoryRules: $.Method<ListInventoryRulesRequest, InventoryRuleList>;

export const GetInventoryProjection: $.Method<InventoryProjectionRequest, InventoryProjection>;
