//  ______                        _               _  _  _
//  |  _  \                      | |             | |(_)| |
//  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_
//  | | | | / _ \  | '_ \  / _ \ | __|  / _ \ / _` || || __|
//  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_
//  |___/   \___/  |_| |_| \___/  \__|  \___| \__,_||_| \__|
//
// Generated by skir-typescript-gen
// Home: https://github.com/gepheum/skir-typescript-gen
//
// To install the Skir client library:
//   npm i skir-client

import * as $ from "skir-client";

// -----------------------------------------------------------------------------
// struct ImportCollectionRequest
// -----------------------------------------------------------------------------

/** Deeply immutable. If you need mutability, use `ImportCollectionRequest.Mutable`. */
export declare class ImportCollectionRequest extends $._FrozenBase {
  /**
   * Creates a new instance of `ImportCollectionRequest`.
   *
   * You must specify all the fields unless you use `create<"partial">({...})>`,
   * in which case missing fields are set to their default values.
   */
  static create<_Wholeness extends "whole" | "partial" = "whole">(
    initializer: ImportCollectionRequest.Initializer<_Wholeness>,
  ): ImportCollectionRequest;

  private constructor();

  readonly importRunId: string;
  readonly sourceName: string;
  readonly sourceChecksum: string;
  readonly rowCount: number;

  /** Returns this instance (no-op). */
  toFrozen(): this;

  /** Returns a mutable shallow copy of this instance. */
  toMutable(): ImportCollectionRequest.Mutable;

  /** Default instance with all fields set to their default values. */
  static readonly DEFAULT: ImportCollectionRequest;

  /** Serializer for `ImportCollectionRequest` instances. */
  static readonly serializer: $.Serializer<ImportCollectionRequest>;

  /** Mutable version of this class. */
  static readonly Mutable: typeof ImportCollectionRequest_Mutable;

  readonly [$._INITIALIZER]: ImportCollectionRequest.Initializer | undefined;
  private readonly FROZEN: undefined;
}

/**
 * Mutable version of `ImportCollectionRequest`.
 *
 * @alias ImportCollectionRequest.Mutable
 */
declare class ImportCollectionRequest_Mutable {
  /**
   * Creates a new mutable instance.
   *
   * Fields not specified in `initializer` will be set to their default values.
   */
  constructor(initializer?: ImportCollectionRequest.Initializer<"partial">);

  importRunId: string;
  sourceName: string;
  sourceChecksum: string;
  rowCount: number;

  /** Returns a deeply-immutable copy of this instance. */
  toFrozen(): ImportCollectionRequest;

  readonly [$._INITIALIZER]: ImportCollectionRequest.Initializer | undefined;
}

export declare namespace ImportCollectionRequest {
  interface _Initializer<_Wholeness extends "whole" | "partial"> {
    readonly importRunId: string;
    readonly sourceName: string;
    readonly sourceChecksum: string;
    readonly rowCount: number;
  }

  export type Initializer<_Wholeness extends "whole" | "partial" = "whole"> =
    _Wholeness extends "whole" ? _Initializer<"whole"> : Partial<_Initializer<"partial">>;

  /** Mutable version of ImportCollectionRequest. */
  export type Mutable = ImportCollectionRequest_Mutable;
  export type OrMutable = ImportCollectionRequest | Mutable;
}

// -----------------------------------------------------------------------------
// enum ImportCollectionResponse
// -----------------------------------------------------------------------------

/** Deeply immutable. */
export declare class ImportCollectionResponse extends $._EnumBase {
  /**
   * Constant indicating an unknown `ImportCollectionResponse` (kind: '?').
   *
   * Default value for fields of type `ImportCollectionResponse`.
   */
  static readonly UNKNOWN: ImportCollectionResponse;
  static readonly ACCEPTED: ImportCollectionResponse;
  static readonly REJECTED: ImportCollectionResponse;

  /** Gets or creates a `ImportCollectionResponse` instance from the given initializer. */
  static create<_Wholeness extends "whole" | "partial" = "whole">(
    initializer: ImportCollectionResponse.Initializer<_Wholeness>,
  ): ImportCollectionResponse;

  /**
   * This instance as the union of all the variant types.
   *
   * Use `union.kind` to determine the variant held by this instance.
   */
  declare readonly union: ImportCollectionResponse.UnionView;

  /** Serializer for `ImportCollectionResponse` instances. */
  static readonly serializer: $.Serializer<ImportCollectionResponse>;
}

export declare namespace ImportCollectionResponse {
  /** Identifies a variant. */
  export type Kind = "UNKNOWN" | "ACCEPTED" | "REJECTED";

  export type Initializer<_Wholeness extends "whole" | "partial" = "whole"> =
    | ImportCollectionResponse
    | "UNKNOWN"
    | "ACCEPTED"
    | "REJECTED";

  /** View of a `ImportCollectionResponse` as a union type. */
  export type UnionView =
    | { kind: "UNKNOWN"; value: undefined }
    | { kind: "ACCEPTED"; value: undefined }
    | { kind: "REJECTED"; value: undefined };
}

// -----------------------------------------------------------------------------
// Methods
// -----------------------------------------------------------------------------

export const ImportCollection: $.Method<ImportCollectionRequest, ImportCollectionResponse>;
