//  ______                        _               _  _  _
//  |  _  \                      | |             | |(_)| |
//  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_
//  | | | | / _ \  | '_ \  / _ \ | __|  / _ \ / _` || || __|
//  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_
//  |___/   \___/  |_| |_| \___/  \__|  \___| \__,_||_| \__|
//
// Generated by skir-typescript-gen
// Home: https://github.com/gepheum/skir-typescript-gen
//
// To install the Skir client library:
//   npm i skir-client

import * as $ from "skir-client";

// -----------------------------------------------------------------------------
// struct ImportStatus
// -----------------------------------------------------------------------------

/** Deeply immutable. If you need mutability, use `ImportStatus.Mutable`. */
export declare class ImportStatus extends $._FrozenBase {
  /**
   * Creates a new instance of `ImportStatus`.
   *
   * You must specify all the fields unless you use `create<"partial">({...})>`,
   * in which case missing fields are set to their default values.
   */
  static create<_Wholeness extends "whole" | "partial" = "whole">(
    initializer: ImportStatus.Initializer<_Wholeness>
  ): ImportStatus;

  private constructor();

  readonly importRunId: string;
  readonly status: string;
  readonly rowCount: number;
  readonly sourceName: string;

  /** Returns this instance (no-op). */
  toFrozen(): this;

  /** Returns a mutable shallow copy of this instance. */
  toMutable(): ImportStatus.Mutable;

  /** Default instance with all fields set to their default values. */
  static readonly DEFAULT: ImportStatus;

  /** Serializer for `ImportStatus` instances. */
  static readonly serializer: $.Serializer<ImportStatus>;

  /** Mutable version of this class. */
  static readonly Mutable: typeof ImportStatus_Mutable;

  readonly [$._INITIALIZER]: ImportStatus.Initializer | undefined;
  private readonly FROZEN: undefined;
}

/**
 * Mutable version of `ImportStatus`.
 *
 * @alias ImportStatus.Mutable
 */
declare class ImportStatus_Mutable {
  /**
   * Creates a new mutable instance.
   *
   * Fields not specified in `initializer` will be set to their default values.
   */
  constructor(initializer?: ImportStatus.Initializer<"partial">);

  importRunId: string;
  status: string;
  rowCount: number;
  sourceName: string;

  /** Returns a deeply-immutable copy of this instance. */
  toFrozen(): ImportStatus;

  readonly [$._INITIALIZER]: ImportStatus.Initializer | undefined;
}

export declare namespace ImportStatus {
  interface _Initializer<_Wholeness extends "whole" | "partial"> {
    readonly importRunId: string;
    readonly status: string;
    readonly rowCount: number;
    readonly sourceName: string;
  }

  export type Initializer<_Wholeness extends "whole" | "partial" = "whole"> =
    _Wholeness extends "whole" ? _Initializer<"whole"> : Partial<_Initializer<"partial">>;

  /** Mutable version of ImportStatus. */
  export type Mutable = ImportStatus_Mutable;
  export type OrMutable = ImportStatus | Mutable;
}

// -----------------------------------------------------------------------------
// struct GetLatestImportStatusRequest
// -----------------------------------------------------------------------------

/** Deeply immutable. If you need mutability, use `GetLatestImportStatusRequest.Mutable`. */
export declare class GetLatestImportStatusRequest extends $._FrozenBase {
  /**
   * Creates a new instance of `GetLatestImportStatusRequest`.
   *
   * You must specify all the fields unless you use `create<"partial">({...})>`,
   * in which case missing fields are set to their default values.
   */
  static create<_Wholeness extends "whole" | "partial" = "whole">(
    initializer: GetLatestImportStatusRequest.Initializer<_Wholeness>
  ): GetLatestImportStatusRequest;

  private constructor();

  readonly unit: boolean;

  /** Returns this instance (no-op). */
  toFrozen(): this;

  /** Returns a mutable shallow copy of this instance. */
  toMutable(): GetLatestImportStatusRequest.Mutable;

  /** Default instance with all fields set to their default values. */
  static readonly DEFAULT: GetLatestImportStatusRequest;

  /** Serializer for `GetLatestImportStatusRequest` instances. */
  static readonly serializer: $.Serializer<GetLatestImportStatusRequest>;

  /** Mutable version of this class. */
  static readonly Mutable: typeof GetLatestImportStatusRequest_Mutable;

  readonly [$._INITIALIZER]: GetLatestImportStatusRequest.Initializer | undefined;
  private readonly FROZEN: undefined;
}

/**
 * Mutable version of `GetLatestImportStatusRequest`.
 *
 * @alias GetLatestImportStatusRequest.Mutable
 */
declare class GetLatestImportStatusRequest_Mutable {
  /**
   * Creates a new mutable instance.
   *
   * Fields not specified in `initializer` will be set to their default values.
   */
  constructor(initializer?: GetLatestImportStatusRequest.Initializer<"partial">);

  unit: boolean;

  /** Returns a deeply-immutable copy of this instance. */
  toFrozen(): GetLatestImportStatusRequest;

  readonly [$._INITIALIZER]: GetLatestImportStatusRequest.Initializer | undefined;
}

export declare namespace GetLatestImportStatusRequest {
  interface _Initializer<_Wholeness extends "whole" | "partial"> {
    readonly unit: boolean;
  }

  export type Initializer<_Wholeness extends "whole" | "partial" = "whole"> =
    _Wholeness extends "whole" ? _Initializer<"whole"> : Partial<_Initializer<"partial">>;

  /** Mutable version of GetLatestImportStatusRequest. */
  export type Mutable = GetLatestImportStatusRequest_Mutable;
  export type OrMutable = GetLatestImportStatusRequest | Mutable;
}

// -----------------------------------------------------------------------------
// Methods
// -----------------------------------------------------------------------------

export const GetLatestImportStatus: $.Method<GetLatestImportStatusRequest, ImportStatus>;
