//  ______                        _               _  _  _
//  |  _  \                      | |             | |(_)| |
//  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_
//  | | | | / _ \  | '_ \  / _ \ | __|  / _ \ / _` || || __|
//  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_
//  |___/   \___/  |_| |_| \___/  \__|  \___| \__,_||_| \__|
//
// Generated by skir-gleam-gen
// Home: https://github.com/gepheum/skir-gleam-gen
//
// To install the Skir client library, run:
//   gleam add skir_client
//
// Do not edit this file manually.

import gleam/dynamic/decode as decode_
import skir_client/method as method_
import skir_client as skir_client_
import skir_client/type_descriptor as type_descriptor_
import skir_client/internal/struct_serializer as struct_serializer_
import gleam/list as list_
import gleam/result as result_
import skir_client/internal/enum_serializer as enum_serializer_

// ==============================================================================
// struct UpdateSettingsRequest
// ==============================================================================

pub type UpdateSettingsRequest {
  UpdateSettingsRequest(
    default_grouping: String,
    default_sort: String,
    /// Stores unrecognized fields from newer schema versions for round-trip compatibility.
    /// Set this to `struct_serializer_.None` when creating values manually.
    unrecognized_: struct_serializer_.UnrecognizedFields(UpdateSettingsRequest),
  )
}

/// The default `UpdateSettingsRequest` with all fields set to their default values.
pub const update_settings_request_default = UpdateSettingsRequest(
  default_grouping: "",
  default_sort: "",
  unrecognized_: struct_serializer_.None,
)

/// Creates a new `UpdateSettingsRequest` with the given field values.
pub fn update_settings_request_new(
  default_grouping: String,
  default_sort: String,
) -> UpdateSettingsRequest {
  UpdateSettingsRequest(
    default_grouping: default_grouping,
    default_sort: default_sort,
    unrecognized_: struct_serializer_.None,
  )
}

/// Returns the serializer for `UpdateSettingsRequest` values.
pub fn update_settings_request_serializer() -> skir_client_.Serializer(UpdateSettingsRequest) {
  let default_sort_serializer = skir_client_.string_serializer()
  let default_grouping_serializer = skir_client_.string_serializer()
  struct_serializer_.new_serializer(
    name: "UpdateSettingsRequest",
    qualified_name: "UpdateSettingsRequest",
    module_path: "settings/commands.skir",
    doc: "",
    ordered_fields: [
      struct_serializer_.field_spec_to_field_adapter(
        name: "default_sort",
        number: 0,
        doc: "",
        default: "",
        type_sig: type_descriptor_.Primitive(type_descriptor_.StringType),
        get: fn(s: UpdateSettingsRequest) { s.default_sort },
        set: fn(s: UpdateSettingsRequest, v: String) { UpdateSettingsRequest(..s, default_sort: v) },
        serializer: struct_serializer_.Eager(default_sort_serializer),
      ),
      struct_serializer_.field_spec_to_field_adapter(
        name: "default_grouping",
        number: 1,
        doc: "",
        default: "",
        type_sig: type_descriptor_.Primitive(type_descriptor_.StringType),
        get: fn(s: UpdateSettingsRequest) { s.default_grouping },
        set: fn(s: UpdateSettingsRequest, v: String) { UpdateSettingsRequest(..s, default_grouping: v) },
        serializer: struct_serializer_.Eager(default_grouping_serializer),
      ),
    ],
    default: update_settings_request_default,
    get_unrecognized: fn(s) { s.unrecognized_ },
    set_unrecognized: fn(s, u) { UpdateSettingsRequest(..s, unrecognized_: u) },
    removed_numbers: [],
    recognized_slot_count: 2,
    decode_dense_json: fn(arr, keep) {
      use #(default_sort, arr) <- result_.try(case arr {
        [] -> Ok(#("", []))
        [elem, ..arr] -> decode_.run(elem, default_sort_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      use #(default_grouping, arr) <- result_.try(case arr {
        [] -> Ok(#("", []))
        [elem, ..arr] -> decode_.run(elem, default_grouping_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      let unrecognized_ = struct_serializer_.make_unrecognized_fields_json(arr, list_.length(arr) + 2, keep)
      Ok(UpdateSettingsRequest(default_sort:, default_grouping:, unrecognized_:))
    },
    decode_binary: fn(bits, slots_to_fill, keep) {
      use #(default_sort, bits) <- result_.try(case slots_to_fill > 0 {
        active if active -> default_sort_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#("", bits))
      })
      use #(default_grouping, bits) <- result_.try(case slots_to_fill > 1 {
        active if active -> default_grouping_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#("", bits))
      })
      Ok(#(UpdateSettingsRequest(default_sort:, default_grouping:, unrecognized_: struct_serializer_.None), bits))
    },
  )
}

// ==============================================================================
// enum UpdateSettingsResponse
// ==============================================================================

pub type UpdateSettingsResponse {
  UpdateSettingsResponseUnknown(enum_serializer_.UnrecognizedVariant(UpdateSettingsResponse))
  UpdateSettingsResponseSuccess
  UpdateSettingsResponseError
}

/// The default `UpdateSettingsResponse` (the unknown variant).
pub const update_settings_response_unknown = UpdateSettingsResponseUnknown(enum_serializer_.None)

/// Returns the serializer for `UpdateSettingsResponse` values.
pub fn update_settings_response_serializer() -> skir_client_.Serializer(UpdateSettingsResponse) {
  enum_serializer_.new_serializer(
    name: "UpdateSettingsResponse",
    qualified_name: "UpdateSettingsResponse",
    module_path: "settings/commands.skir",
    doc: "",
    variants: [
      enum_serializer_.constant_variant(
        name: "success",
        number: 1,
        doc: "",
        instance: UpdateSettingsResponseSuccess,
      ),
      enum_serializer_.constant_variant(
        name: "error",
        number: 2,
        doc: "",
        instance: UpdateSettingsResponseError,
      ),
    ],
    unknown_default: update_settings_response_unknown,
    get_kind_ordinal: fn(e) {
      case e {
        UpdateSettingsResponseUnknown(_) -> 0
        UpdateSettingsResponseSuccess -> 1
        UpdateSettingsResponseError -> 2
      }
    },
    wrap_unrecognized: fn(u) { UpdateSettingsResponseUnknown(u) },
    get_unrecognized: fn(e) {
      case e {
        UpdateSettingsResponseUnknown(u) -> u
        _ -> enum_serializer_.None
      }
    },
    removed_numbers: [],
  )
}

// ==============================================================================
// method UpdateSettings
// ==============================================================================

pub fn update_settings_method() -> method_.Method(UpdateSettingsRequest, UpdateSettingsResponse) {
  method_.Method(
    name: "UpdateSettings",
    number: 401,
    doc: "",
    request_serializer: update_settings_request_serializer(),
    response_serializer: update_settings_response_serializer(),
  )
}
