//  ______                        _               _  _  _
//  |  _  \                      | |             | |(_)| |
//  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_
//  | | | | / _ \  | '_ \  / _ \ | __|  / _ \ / _` || || __|
//  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_
//  |___/   \___/  |_| |_| \___/  \__|  \___| \__,_||_| \__|
//
// Generated by skir-gleam-gen
// Home: https://github.com/gepheum/skir-gleam-gen
//
// To install the Skir client library, run:
//   gleam add skir_client
//
// Do not edit this file manually.

import gleam/dynamic/decode as decode_
import skir_client/method as method_
import skir_client as skir_client_
import skir_client/type_descriptor as type_descriptor_
import skir_client/internal/struct_serializer as struct_serializer_
import gleam/list as list_
import gleam/result as result_

// ==============================================================================
// struct AppSettings
// ==============================================================================

pub type AppSettings {
  AppSettings(
    default_grouping: String,
    default_sort: String,
    /// Stores unrecognized fields from newer schema versions for round-trip compatibility.
    /// Set this to `struct_serializer_.None` when creating values manually.
    unrecognized_: struct_serializer_.UnrecognizedFields(AppSettings),
  )
}

/// The default `AppSettings` with all fields set to their default values.
pub const app_settings_default = AppSettings(
  default_grouping: "",
  default_sort: "",
  unrecognized_: struct_serializer_.None,
)

/// Creates a new `AppSettings` with the given field values.
pub fn app_settings_new(
  default_grouping: String,
  default_sort: String,
) -> AppSettings {
  AppSettings(
    default_grouping: default_grouping,
    default_sort: default_sort,
    unrecognized_: struct_serializer_.None,
  )
}

/// Returns the serializer for `AppSettings` values.
pub fn app_settings_serializer() -> skir_client_.Serializer(AppSettings) {
  let default_sort_serializer = skir_client_.string_serializer()
  let default_grouping_serializer = skir_client_.string_serializer()
  struct_serializer_.new_serializer(
    name: "AppSettings",
    qualified_name: "AppSettings",
    module_path: "settings/queries.skir",
    doc: "",
    ordered_fields: [
      struct_serializer_.field_spec_to_field_adapter(
        name: "default_sort",
        number: 0,
        doc: "",
        default: "",
        type_sig: type_descriptor_.Primitive(type_descriptor_.StringType),
        get: fn(s: AppSettings) { s.default_sort },
        set: fn(s: AppSettings, v: String) { AppSettings(..s, default_sort: v) },
        serializer: struct_serializer_.Eager(default_sort_serializer),
      ),
      struct_serializer_.field_spec_to_field_adapter(
        name: "default_grouping",
        number: 1,
        doc: "",
        default: "",
        type_sig: type_descriptor_.Primitive(type_descriptor_.StringType),
        get: fn(s: AppSettings) { s.default_grouping },
        set: fn(s: AppSettings, v: String) { AppSettings(..s, default_grouping: v) },
        serializer: struct_serializer_.Eager(default_grouping_serializer),
      ),
    ],
    default: app_settings_default,
    get_unrecognized: fn(s) { s.unrecognized_ },
    set_unrecognized: fn(s, u) { AppSettings(..s, unrecognized_: u) },
    removed_numbers: [],
    recognized_slot_count: 2,
    decode_dense_json: fn(arr, keep) {
      use #(default_sort, arr) <- result_.try(case arr {
        [] -> Ok(#("", []))
        [elem, ..arr] -> decode_.run(elem, default_sort_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      use #(default_grouping, arr) <- result_.try(case arr {
        [] -> Ok(#("", []))
        [elem, ..arr] -> decode_.run(elem, default_grouping_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      let unrecognized_ = struct_serializer_.make_unrecognized_fields_json(arr, list_.length(arr) + 2, keep)
      Ok(AppSettings(default_sort:, default_grouping:, unrecognized_:))
    },
    decode_binary: fn(bits, slots_to_fill, keep) {
      use #(default_sort, bits) <- result_.try(case slots_to_fill > 0 {
        active if active -> default_sort_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#("", bits))
      })
      use #(default_grouping, bits) <- result_.try(case slots_to_fill > 1 {
        active if active -> default_grouping_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#("", bits))
      })
      Ok(#(AppSettings(default_sort:, default_grouping:, unrecognized_: struct_serializer_.None), bits))
    },
  )
}

// ==============================================================================
// struct GetSettingsRequest
// ==============================================================================

pub type GetSettingsRequest {
  GetSettingsRequest(
    unit: Bool,
    /// Stores unrecognized fields from newer schema versions for round-trip compatibility.
    /// Set this to `struct_serializer_.None` when creating values manually.
    unrecognized_: struct_serializer_.UnrecognizedFields(GetSettingsRequest),
  )
}

/// The default `GetSettingsRequest` with all fields set to their default values.
pub const get_settings_request_default = GetSettingsRequest(
  unit: False,
  unrecognized_: struct_serializer_.None,
)

/// Creates a new `GetSettingsRequest` with the given field values.
pub fn get_settings_request_new(
  unit: Bool,
) -> GetSettingsRequest {
  GetSettingsRequest(
    unit: unit,
    unrecognized_: struct_serializer_.None,
  )
}

/// Returns the serializer for `GetSettingsRequest` values.
pub fn get_settings_request_serializer() -> skir_client_.Serializer(GetSettingsRequest) {
  let unit_serializer = skir_client_.bool_serializer()
  struct_serializer_.new_serializer(
    name: "GetSettingsRequest",
    qualified_name: "GetSettingsRequest",
    module_path: "settings/queries.skir",
    doc: "",
    ordered_fields: [
      struct_serializer_.field_spec_to_field_adapter(
        name: "unit",
        number: 0,
        doc: "",
        default: False,
        type_sig: type_descriptor_.Primitive(type_descriptor_.Bool),
        get: fn(s: GetSettingsRequest) { s.unit },
        set: fn(s: GetSettingsRequest, v: Bool) { GetSettingsRequest(..s, unit: v) },
        serializer: struct_serializer_.Eager(unit_serializer),
      ),
    ],
    default: get_settings_request_default,
    get_unrecognized: fn(s) { s.unrecognized_ },
    set_unrecognized: fn(s, u) { GetSettingsRequest(..s, unrecognized_: u) },
    removed_numbers: [],
    recognized_slot_count: 1,
    decode_dense_json: fn(arr, keep) {
      use #(unit, arr) <- result_.try(case arr {
        [] -> Ok(#(False, []))
        [elem, ..arr] -> decode_.run(elem, unit_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      let unrecognized_ = struct_serializer_.make_unrecognized_fields_json(arr, list_.length(arr) + 1, keep)
      Ok(GetSettingsRequest(unit:, unrecognized_:))
    },
    decode_binary: fn(bits, slots_to_fill, keep) {
      use #(unit, bits) <- result_.try(case slots_to_fill > 0 {
        active if active -> unit_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#(False, bits))
      })
      Ok(#(GetSettingsRequest(unit:, unrecognized_: struct_serializer_.None), bits))
    },
  )
}

// ==============================================================================
// method GetSettings
// ==============================================================================

pub fn get_settings_method() -> method_.Method(GetSettingsRequest, AppSettings) {
  method_.Method(
    name: "GetSettings",
    number: 402,
    doc: "",
    request_serializer: get_settings_request_serializer(),
    response_serializer: app_settings_serializer(),
  )
}
