//  ______                        _               _  _  _
//  |  _  \                      | |             | |(_)| |
//  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_
//  | | | | / _ \  | '_ \  / _ \ | __|  / _ \ / _` || || __|
//  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_
//  |___/   \___/  |_| |_| \___/  \__|  \___| \__,_||_| \__|
//
// Generated by skir-typescript-gen
// Home: https://github.com/gepheum/skir-typescript-gen
//
// To install the Skir client library:
//   npm i skir-client

import * as $ from "skir-client";

// -----------------------------------------------------------------------------
// struct UpdateSettingsRequest
// -----------------------------------------------------------------------------

/** Deeply immutable. If you need mutability, use `UpdateSettingsRequest.Mutable`. */
export declare class UpdateSettingsRequest extends $._FrozenBase {
  /**
   * Creates a new instance of `UpdateSettingsRequest`.
   *
   * You must specify all the fields unless you use `create<"partial">({...})>`,
   * in which case missing fields are set to their default values.
   */
  static create<_Wholeness extends "whole" | "partial" = "whole">(
    initializer: UpdateSettingsRequest.Initializer<_Wholeness>,
  ): UpdateSettingsRequest;

  private constructor();

  readonly defaultSort: string;
  readonly defaultGrouping: string;

  /** Returns this instance (no-op). */
  toFrozen(): this;

  /** Returns a mutable shallow copy of this instance. */
  toMutable(): UpdateSettingsRequest.Mutable;

  /** Default instance with all fields set to their default values. */
  static readonly DEFAULT: UpdateSettingsRequest;

  /** Serializer for `UpdateSettingsRequest` instances. */
  static readonly serializer: $.Serializer<UpdateSettingsRequest>;

  /** Mutable version of this class. */
  static readonly Mutable: typeof UpdateSettingsRequest_Mutable;

  readonly [$._INITIALIZER]: UpdateSettingsRequest.Initializer | undefined;
  private readonly FROZEN: undefined;
}

/**
 * Mutable version of `UpdateSettingsRequest`.
 *
 * @alias UpdateSettingsRequest.Mutable
 */
declare class UpdateSettingsRequest_Mutable {
  /**
   * Creates a new mutable instance.
   *
   * Fields not specified in `initializer` will be set to their default values.
   */
  constructor(initializer?: UpdateSettingsRequest.Initializer<"partial">);

  defaultSort: string;
  defaultGrouping: string;

  /** Returns a deeply-immutable copy of this instance. */
  toFrozen(): UpdateSettingsRequest;

  readonly [$._INITIALIZER]: UpdateSettingsRequest.Initializer | undefined;
}

export declare namespace UpdateSettingsRequest {
  interface _Initializer<_Wholeness extends "whole" | "partial"> {
    readonly defaultSort: string;
    readonly defaultGrouping: string;
  }

  export type Initializer<_Wholeness extends "whole" | "partial" = "whole"> =
    _Wholeness extends "whole" ? _Initializer<"whole"> : Partial<_Initializer<"partial">>;

  /** Mutable version of UpdateSettingsRequest. */
  export type Mutable = UpdateSettingsRequest_Mutable;
  export type OrMutable = UpdateSettingsRequest | Mutable;
}

// -----------------------------------------------------------------------------
// enum UpdateSettingsResponse
// -----------------------------------------------------------------------------

/** Deeply immutable. */
export declare class UpdateSettingsResponse extends $._EnumBase {
  /**
   * Constant indicating an unknown `UpdateSettingsResponse` (kind: '?').
   *
   * Default value for fields of type `UpdateSettingsResponse`.
   */
  static readonly UNKNOWN: UpdateSettingsResponse;
  static readonly SUCCESS: UpdateSettingsResponse;
  static readonly ERROR: UpdateSettingsResponse;

  /** Gets or creates a `UpdateSettingsResponse` instance from the given initializer. */
  static create<_Wholeness extends "whole" | "partial" = "whole">(
    initializer: UpdateSettingsResponse.Initializer<_Wholeness>,
  ): UpdateSettingsResponse;

  /**
   * This instance as the union of all the variant types.
   *
   * Use `union.kind` to determine the variant held by this instance.
   */
  declare readonly union: UpdateSettingsResponse.UnionView;

  /** Serializer for `UpdateSettingsResponse` instances. */
  static readonly serializer: $.Serializer<UpdateSettingsResponse>;
}

export declare namespace UpdateSettingsResponse {
  /** Identifies a variant. */
  export type Kind = "UNKNOWN" | "SUCCESS" | "ERROR";

  export type Initializer<_Wholeness extends "whole" | "partial" = "whole"> =
    | UpdateSettingsResponse
    | "UNKNOWN"
    | "SUCCESS"
    | "ERROR";

  /** View of a `UpdateSettingsResponse` as a union type. */
  export type UnionView =
    | { kind: "UNKNOWN"; value: undefined }
    | { kind: "SUCCESS"; value: undefined }
    | { kind: "ERROR"; value: undefined };
}

// -----------------------------------------------------------------------------
// Methods
// -----------------------------------------------------------------------------

export const UpdateSettings: $.Method<UpdateSettingsRequest, UpdateSettingsResponse>;
