//  ______                        _               _  _  _
//  |  _  \                      | |             | |(_)| |
//  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_
//  | | | | / _ \  | '_ \  / _ \ | __|  / _ \ / _` || || __|
//  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_
//  |___/   \___/  |_| |_| \___/  \__|  \___| \__,_||_| \__|
//
// Generated by skir-typescript-gen
// Home: https://github.com/gepheum/skir-typescript-gen
//
// To install the Skir client library:
//   npm i skir-client

import * as $ from "skir-client";

// -----------------------------------------------------------------------------
// struct AppSettings
// -----------------------------------------------------------------------------

/** Deeply immutable. If you need mutability, use `AppSettings.Mutable`. */
export declare class AppSettings extends $._FrozenBase {
  /**
   * Creates a new instance of `AppSettings`.
   *
   * You must specify all the fields unless you use `create<"partial">({...})>`,
   * in which case missing fields are set to their default values.
   */
  static create<_Wholeness extends "whole" | "partial" = "whole">(
    initializer: AppSettings.Initializer<_Wholeness>
  ): AppSettings;

  private constructor();

  readonly defaultSort: string;
  readonly defaultGrouping: string;

  /** Returns this instance (no-op). */
  toFrozen(): this;

  /** Returns a mutable shallow copy of this instance. */
  toMutable(): AppSettings.Mutable;

  /** Default instance with all fields set to their default values. */
  static readonly DEFAULT: AppSettings;

  /** Serializer for `AppSettings` instances. */
  static readonly serializer: $.Serializer<AppSettings>;

  /** Mutable version of this class. */
  static readonly Mutable: typeof AppSettings_Mutable;

  readonly [$._INITIALIZER]: AppSettings.Initializer | undefined;
  private readonly FROZEN: undefined;
}

/**
 * Mutable version of `AppSettings`.
 *
 * @alias AppSettings.Mutable
 */
declare class AppSettings_Mutable {
  /**
   * Creates a new mutable instance.
   *
   * Fields not specified in `initializer` will be set to their default values.
   */
  constructor(initializer?: AppSettings.Initializer<"partial">);

  defaultSort: string;
  defaultGrouping: string;

  /** Returns a deeply-immutable copy of this instance. */
  toFrozen(): AppSettings;

  readonly [$._INITIALIZER]: AppSettings.Initializer | undefined;
}

export declare namespace AppSettings {
  interface _Initializer<_Wholeness extends "whole" | "partial"> {
    readonly defaultSort: string;
    readonly defaultGrouping: string;
  }

  export type Initializer<_Wholeness extends "whole" | "partial" = "whole"> =
    _Wholeness extends "whole" ? _Initializer<"whole"> : Partial<_Initializer<"partial">>;

  /** Mutable version of AppSettings. */
  export type Mutable = AppSettings_Mutable;
  export type OrMutable = AppSettings | Mutable;
}

// -----------------------------------------------------------------------------
// struct GetSettingsRequest
// -----------------------------------------------------------------------------

/** Deeply immutable. If you need mutability, use `GetSettingsRequest.Mutable`. */
export declare class GetSettingsRequest extends $._FrozenBase {
  /**
   * Creates a new instance of `GetSettingsRequest`.
   *
   * You must specify all the fields unless you use `create<"partial">({...})>`,
   * in which case missing fields are set to their default values.
   */
  static create<_Wholeness extends "whole" | "partial" = "whole">(
    initializer: GetSettingsRequest.Initializer<_Wholeness>
  ): GetSettingsRequest;

  private constructor();

  readonly unit: boolean;

  /** Returns this instance (no-op). */
  toFrozen(): this;

  /** Returns a mutable shallow copy of this instance. */
  toMutable(): GetSettingsRequest.Mutable;

  /** Default instance with all fields set to their default values. */
  static readonly DEFAULT: GetSettingsRequest;

  /** Serializer for `GetSettingsRequest` instances. */
  static readonly serializer: $.Serializer<GetSettingsRequest>;

  /** Mutable version of this class. */
  static readonly Mutable: typeof GetSettingsRequest_Mutable;

  readonly [$._INITIALIZER]: GetSettingsRequest.Initializer | undefined;
  private readonly FROZEN: undefined;
}

/**
 * Mutable version of `GetSettingsRequest`.
 *
 * @alias GetSettingsRequest.Mutable
 */
declare class GetSettingsRequest_Mutable {
  /**
   * Creates a new mutable instance.
   *
   * Fields not specified in `initializer` will be set to their default values.
   */
  constructor(initializer?: GetSettingsRequest.Initializer<"partial">);

  unit: boolean;

  /** Returns a deeply-immutable copy of this instance. */
  toFrozen(): GetSettingsRequest;

  readonly [$._INITIALIZER]: GetSettingsRequest.Initializer | undefined;
}

export declare namespace GetSettingsRequest {
  interface _Initializer<_Wholeness extends "whole" | "partial"> {
    readonly unit: boolean;
  }

  export type Initializer<_Wholeness extends "whole" | "partial" = "whole"> =
    _Wholeness extends "whole" ? _Initializer<"whole"> : Partial<_Initializer<"partial">>;

  /** Mutable version of GetSettingsRequest. */
  export type Mutable = GetSettingsRequest_Mutable;
  export type OrMutable = GetSettingsRequest | Mutable;
}

// -----------------------------------------------------------------------------
// Methods
// -----------------------------------------------------------------------------

export const GetSettings: $.Method<GetSettingsRequest, AppSettings>;
