default: dev

setup:
  gleam deps download

build:
  gleam build

format:
  find src test -type f -name '*.gleam' ! -path '*/skirout/*' | xargs gleam format

[group('check')]
format-check:
  find src test -type f -name '*.gleam' ! -path '*/skirout/*' | xargs gleam format --check

[group('check')]
type-check:
  gleam check

[group('check')]
lint-check:
  gleam run -m lint

[group('check')]
check: format-check type-check lint-check

[group('test')]
test:
  gleam test

run:
  mkdir -p db
  export TCG_DB_FILE=db/tcg-card-collector.db
  ../scripts/dbmate_up.sh
  gleam run

[group('dev')]
dev: run
