//  ______                        _               _  _  _
//  |  _  \                      | |             | |(_)| |
//  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_
//  | | | | / _ \  | '_ \  / _ \ | __|  / _ \ / _` || || __|
//  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_
//  |___/   \___/  |_| |_| \___/  \__|  \___| \__,_||_| \__|
//
// Generated by skir-gleam-gen
// Home: https://github.com/gepheum/skir-gleam-gen
//
// To install the Skir client library, run:
//   gleam add skir_client
//
// Do not edit this file manually.

import gleam/dynamic/decode as decode_
import skir_client/method as method_
import skir_client as skir_client_
import skir_client/type_descriptor as type_descriptor_
import skir_client/internal/struct_serializer as struct_serializer_
import gleam/list as list_
import gleam/result as result_
import skir_client/internal/enum_serializer as enum_serializer_

// ==============================================================================
// struct UpsertInventoryRuleRequest
// ==============================================================================

pub type UpsertInventoryRuleRequest {
  UpsertInventoryRuleRequest(
    expression: String,
    id: String,
    location_name: String,
    /// Stores unrecognized fields from newer schema versions for round-trip compatibility.
    /// Set this to `struct_serializer_.None` when creating values manually.
    unrecognized_: struct_serializer_.UnrecognizedFields(UpsertInventoryRuleRequest),
  )
}

/// The default `UpsertInventoryRuleRequest` with all fields set to their default values.
pub const upsert_inventory_rule_request_default = UpsertInventoryRuleRequest(
  expression: "",
  id: "",
  location_name: "",
  unrecognized_: struct_serializer_.None,
)

/// Creates a new `UpsertInventoryRuleRequest` with the given field values.
pub fn upsert_inventory_rule_request_new(
  expression: String,
  id: String,
  location_name: String,
) -> UpsertInventoryRuleRequest {
  UpsertInventoryRuleRequest(
    expression: expression,
    id: id,
    location_name: location_name,
    unrecognized_: struct_serializer_.None,
  )
}

/// Returns the serializer for `UpsertInventoryRuleRequest` values.
pub fn upsert_inventory_rule_request_serializer() -> skir_client_.Serializer(UpsertInventoryRuleRequest) {
  let id_serializer = skir_client_.string_serializer()
  let location_name_serializer = skir_client_.string_serializer()
  let expression_serializer = skir_client_.string_serializer()
  struct_serializer_.new_serializer(
    name: "UpsertInventoryRuleRequest",
    qualified_name: "UpsertInventoryRuleRequest",
    module_path: "inventory_planning/commands.skir",
    doc: "",
    ordered_fields: [
      struct_serializer_.field_spec_to_field_adapter(
        name: "id",
        number: 0,
        doc: "",
        default: "",
        type_sig: type_descriptor_.Primitive(type_descriptor_.StringType),
        get: fn(s: UpsertInventoryRuleRequest) { s.id },
        set: fn(s: UpsertInventoryRuleRequest, v: String) { UpsertInventoryRuleRequest(..s, id: v) },
        serializer: struct_serializer_.Eager(id_serializer),
      ),
      struct_serializer_.field_spec_to_field_adapter(
        name: "location_name",
        number: 1,
        doc: "",
        default: "",
        type_sig: type_descriptor_.Primitive(type_descriptor_.StringType),
        get: fn(s: UpsertInventoryRuleRequest) { s.location_name },
        set: fn(s: UpsertInventoryRuleRequest, v: String) { UpsertInventoryRuleRequest(..s, location_name: v) },
        serializer: struct_serializer_.Eager(location_name_serializer),
      ),
      struct_serializer_.field_spec_to_field_adapter(
        name: "expression",
        number: 2,
        doc: "",
        default: "",
        type_sig: type_descriptor_.Primitive(type_descriptor_.StringType),
        get: fn(s: UpsertInventoryRuleRequest) { s.expression },
        set: fn(s: UpsertInventoryRuleRequest, v: String) { UpsertInventoryRuleRequest(..s, expression: v) },
        serializer: struct_serializer_.Eager(expression_serializer),
      ),
    ],
    default: upsert_inventory_rule_request_default,
    get_unrecognized: fn(s) { s.unrecognized_ },
    set_unrecognized: fn(s, u) { UpsertInventoryRuleRequest(..s, unrecognized_: u) },
    removed_numbers: [],
    recognized_slot_count: 3,
    decode_dense_json: fn(arr, keep) {
      use #(id, arr) <- result_.try(case arr {
        [] -> Ok(#("", []))
        [elem, ..arr] -> decode_.run(elem, id_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      use #(location_name, arr) <- result_.try(case arr {
        [] -> Ok(#("", []))
        [elem, ..arr] -> decode_.run(elem, location_name_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      use #(expression, arr) <- result_.try(case arr {
        [] -> Ok(#("", []))
        [elem, ..arr] -> decode_.run(elem, expression_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      let unrecognized_ = struct_serializer_.make_unrecognized_fields_json(arr, list_.length(arr) + 3, keep)
      Ok(UpsertInventoryRuleRequest(id:, location_name:, expression:, unrecognized_:))
    },
    decode_binary: fn(bits, slots_to_fill, keep) {
      use #(id, bits) <- result_.try(case slots_to_fill > 0 {
        active if active -> id_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#("", bits))
      })
      use #(location_name, bits) <- result_.try(case slots_to_fill > 1 {
        active if active -> location_name_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#("", bits))
      })
      use #(expression, bits) <- result_.try(case slots_to_fill > 2 {
        active if active -> expression_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#("", bits))
      })
      Ok(#(UpsertInventoryRuleRequest(id:, location_name:, expression:, unrecognized_: struct_serializer_.None), bits))
    },
  )
}

// ==============================================================================
// enum UpsertInventoryRuleResponse
// ==============================================================================

pub type UpsertInventoryRuleResponse {
  UpsertInventoryRuleResponseUnknown(enum_serializer_.UnrecognizedVariant(UpsertInventoryRuleResponse))
  UpsertInventoryRuleResponseSuccess
  UpsertInventoryRuleResponseError
}

/// The default `UpsertInventoryRuleResponse` (the unknown variant).
pub const upsert_inventory_rule_response_unknown = UpsertInventoryRuleResponseUnknown(enum_serializer_.None)

/// Returns the serializer for `UpsertInventoryRuleResponse` values.
pub fn upsert_inventory_rule_response_serializer() -> skir_client_.Serializer(UpsertInventoryRuleResponse) {
  enum_serializer_.new_serializer(
    name: "UpsertInventoryRuleResponse",
    qualified_name: "UpsertInventoryRuleResponse",
    module_path: "inventory_planning/commands.skir",
    doc: "",
    variants: [
      enum_serializer_.constant_variant(
        name: "success",
        number: 1,
        doc: "",
        instance: UpsertInventoryRuleResponseSuccess,
      ),
      enum_serializer_.constant_variant(
        name: "error",
        number: 2,
        doc: "",
        instance: UpsertInventoryRuleResponseError,
      ),
    ],
    unknown_default: upsert_inventory_rule_response_unknown,
    get_kind_ordinal: fn(e) {
      case e {
        UpsertInventoryRuleResponseUnknown(_) -> 0
        UpsertInventoryRuleResponseSuccess -> 1
        UpsertInventoryRuleResponseError -> 2
      }
    },
    wrap_unrecognized: fn(u) { UpsertInventoryRuleResponseUnknown(u) },
    get_unrecognized: fn(e) {
      case e {
        UpsertInventoryRuleResponseUnknown(u) -> u
        _ -> enum_serializer_.None
      }
    },
    removed_numbers: [],
  )
}

// ==============================================================================
// struct DeleteInventoryRuleRequest
// ==============================================================================

pub type DeleteInventoryRuleRequest {
  DeleteInventoryRuleRequest(
    id: String,
    /// Stores unrecognized fields from newer schema versions for round-trip compatibility.
    /// Set this to `struct_serializer_.None` when creating values manually.
    unrecognized_: struct_serializer_.UnrecognizedFields(DeleteInventoryRuleRequest),
  )
}

/// The default `DeleteInventoryRuleRequest` with all fields set to their default values.
pub const delete_inventory_rule_request_default = DeleteInventoryRuleRequest(
  id: "",
  unrecognized_: struct_serializer_.None,
)

/// Creates a new `DeleteInventoryRuleRequest` with the given field values.
pub fn delete_inventory_rule_request_new(
  id: String,
) -> DeleteInventoryRuleRequest {
  DeleteInventoryRuleRequest(
    id: id,
    unrecognized_: struct_serializer_.None,
  )
}

/// Returns the serializer for `DeleteInventoryRuleRequest` values.
pub fn delete_inventory_rule_request_serializer() -> skir_client_.Serializer(DeleteInventoryRuleRequest) {
  let id_serializer = skir_client_.string_serializer()
  struct_serializer_.new_serializer(
    name: "DeleteInventoryRuleRequest",
    qualified_name: "DeleteInventoryRuleRequest",
    module_path: "inventory_planning/commands.skir",
    doc: "",
    ordered_fields: [
      struct_serializer_.field_spec_to_field_adapter(
        name: "id",
        number: 0,
        doc: "",
        default: "",
        type_sig: type_descriptor_.Primitive(type_descriptor_.StringType),
        get: fn(s: DeleteInventoryRuleRequest) { s.id },
        set: fn(s: DeleteInventoryRuleRequest, v: String) { DeleteInventoryRuleRequest(..s, id: v) },
        serializer: struct_serializer_.Eager(id_serializer),
      ),
    ],
    default: delete_inventory_rule_request_default,
    get_unrecognized: fn(s) { s.unrecognized_ },
    set_unrecognized: fn(s, u) { DeleteInventoryRuleRequest(..s, unrecognized_: u) },
    removed_numbers: [],
    recognized_slot_count: 1,
    decode_dense_json: fn(arr, keep) {
      use #(id, arr) <- result_.try(case arr {
        [] -> Ok(#("", []))
        [elem, ..arr] -> decode_.run(elem, id_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      let unrecognized_ = struct_serializer_.make_unrecognized_fields_json(arr, list_.length(arr) + 1, keep)
      Ok(DeleteInventoryRuleRequest(id:, unrecognized_:))
    },
    decode_binary: fn(bits, slots_to_fill, keep) {
      use #(id, bits) <- result_.try(case slots_to_fill > 0 {
        active if active -> id_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#("", bits))
      })
      Ok(#(DeleteInventoryRuleRequest(id:, unrecognized_: struct_serializer_.None), bits))
    },
  )
}

// ==============================================================================
// enum DeleteInventoryRuleResponse
// ==============================================================================

pub type DeleteInventoryRuleResponse {
  DeleteInventoryRuleResponseUnknown(enum_serializer_.UnrecognizedVariant(DeleteInventoryRuleResponse))
  DeleteInventoryRuleResponseSuccess
  DeleteInventoryRuleResponseError
}

/// The default `DeleteInventoryRuleResponse` (the unknown variant).
pub const delete_inventory_rule_response_unknown = DeleteInventoryRuleResponseUnknown(enum_serializer_.None)

/// Returns the serializer for `DeleteInventoryRuleResponse` values.
pub fn delete_inventory_rule_response_serializer() -> skir_client_.Serializer(DeleteInventoryRuleResponse) {
  enum_serializer_.new_serializer(
    name: "DeleteInventoryRuleResponse",
    qualified_name: "DeleteInventoryRuleResponse",
    module_path: "inventory_planning/commands.skir",
    doc: "",
    variants: [
      enum_serializer_.constant_variant(
        name: "success",
        number: 1,
        doc: "",
        instance: DeleteInventoryRuleResponseSuccess,
      ),
      enum_serializer_.constant_variant(
        name: "error",
        number: 2,
        doc: "",
        instance: DeleteInventoryRuleResponseError,
      ),
    ],
    unknown_default: delete_inventory_rule_response_unknown,
    get_kind_ordinal: fn(e) {
      case e {
        DeleteInventoryRuleResponseUnknown(_) -> 0
        DeleteInventoryRuleResponseSuccess -> 1
        DeleteInventoryRuleResponseError -> 2
      }
    },
    wrap_unrecognized: fn(u) { DeleteInventoryRuleResponseUnknown(u) },
    get_unrecognized: fn(e) {
      case e {
        DeleteInventoryRuleResponseUnknown(u) -> u
        _ -> enum_serializer_.None
      }
    },
    removed_numbers: [],
  )
}

// ==============================================================================
// method UpsertInventoryRule
// ==============================================================================

pub fn upsert_inventory_rule_method() -> method_.Method(UpsertInventoryRuleRequest, UpsertInventoryRuleResponse) {
  method_.Method(
    name: "UpsertInventoryRule",
    number: 301,
    doc: "",
    request_serializer: upsert_inventory_rule_request_serializer(),
    response_serializer: upsert_inventory_rule_response_serializer(),
  )
}

// ==============================================================================
// method DeleteInventoryRule
// ==============================================================================

pub fn delete_inventory_rule_method() -> method_.Method(DeleteInventoryRuleRequest, DeleteInventoryRuleResponse) {
  method_.Method(
    name: "DeleteInventoryRule",
    number: 302,
    doc: "",
    request_serializer: delete_inventory_rule_request_serializer(),
    response_serializer: delete_inventory_rule_response_serializer(),
  )
}
