//  ______                        _               _  _  _
//  |  _  \                      | |             | |(_)| |
//  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_
//  | | | | / _ \  | '_ \  / _ \ | __|  / _ \ / _` || || __|
//  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_
//  |___/   \___/  |_| |_| \___/  \__|  \___| \__,_||_| \__|
//
// Generated by skir-gleam-gen
// Home: https://github.com/gepheum/skir-gleam-gen
//
// To install the Skir client library, run:
//   gleam add skir_client
//
// Do not edit this file manually.

import gleam/dynamic/decode as decode_
import skir_client/method as method_
import skir_client as skir_client_
import skir_client/type_descriptor as type_descriptor_
import skir_client/internal/struct_serializer as struct_serializer_
import gleam/list as list_
import gleam/result as result_

// ==============================================================================
// struct InventoryRule
// ==============================================================================

pub type InventoryRule {
  InventoryRule(
    expression: String,
    id: String,
    location_name: String,
    /// Stores unrecognized fields from newer schema versions for round-trip compatibility.
    /// Set this to `struct_serializer_.None` when creating values manually.
    unrecognized_: struct_serializer_.UnrecognizedFields(InventoryRule),
  )
}

/// The default `InventoryRule` with all fields set to their default values.
pub const inventory_rule_default = InventoryRule(
  expression: "",
  id: "",
  location_name: "",
  unrecognized_: struct_serializer_.None,
)

/// Creates a new `InventoryRule` with the given field values.
pub fn inventory_rule_new(
  expression: String,
  id: String,
  location_name: String,
) -> InventoryRule {
  InventoryRule(
    expression: expression,
    id: id,
    location_name: location_name,
    unrecognized_: struct_serializer_.None,
  )
}

/// Returns the serializer for `InventoryRule` values.
pub fn inventory_rule_serializer() -> skir_client_.Serializer(InventoryRule) {
  let id_serializer = skir_client_.string_serializer()
  let location_name_serializer = skir_client_.string_serializer()
  let expression_serializer = skir_client_.string_serializer()
  struct_serializer_.new_serializer(
    name: "InventoryRule",
    qualified_name: "InventoryRule",
    module_path: "inventory_planning/queries.skir",
    doc: "",
    ordered_fields: [
      struct_serializer_.field_spec_to_field_adapter(
        name: "id",
        number: 0,
        doc: "",
        default: "",
        type_sig: type_descriptor_.Primitive(type_descriptor_.StringType),
        get: fn(s: InventoryRule) { s.id },
        set: fn(s: InventoryRule, v: String) { InventoryRule(..s, id: v) },
        serializer: struct_serializer_.Eager(id_serializer),
      ),
      struct_serializer_.field_spec_to_field_adapter(
        name: "location_name",
        number: 1,
        doc: "",
        default: "",
        type_sig: type_descriptor_.Primitive(type_descriptor_.StringType),
        get: fn(s: InventoryRule) { s.location_name },
        set: fn(s: InventoryRule, v: String) { InventoryRule(..s, location_name: v) },
        serializer: struct_serializer_.Eager(location_name_serializer),
      ),
      struct_serializer_.field_spec_to_field_adapter(
        name: "expression",
        number: 2,
        doc: "",
        default: "",
        type_sig: type_descriptor_.Primitive(type_descriptor_.StringType),
        get: fn(s: InventoryRule) { s.expression },
        set: fn(s: InventoryRule, v: String) { InventoryRule(..s, expression: v) },
        serializer: struct_serializer_.Eager(expression_serializer),
      ),
    ],
    default: inventory_rule_default,
    get_unrecognized: fn(s) { s.unrecognized_ },
    set_unrecognized: fn(s, u) { InventoryRule(..s, unrecognized_: u) },
    removed_numbers: [],
    recognized_slot_count: 3,
    decode_dense_json: fn(arr, keep) {
      use #(id, arr) <- result_.try(case arr {
        [] -> Ok(#("", []))
        [elem, ..arr] -> decode_.run(elem, id_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      use #(location_name, arr) <- result_.try(case arr {
        [] -> Ok(#("", []))
        [elem, ..arr] -> decode_.run(elem, location_name_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      use #(expression, arr) <- result_.try(case arr {
        [] -> Ok(#("", []))
        [elem, ..arr] -> decode_.run(elem, expression_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      let unrecognized_ = struct_serializer_.make_unrecognized_fields_json(arr, list_.length(arr) + 3, keep)
      Ok(InventoryRule(id:, location_name:, expression:, unrecognized_:))
    },
    decode_binary: fn(bits, slots_to_fill, keep) {
      use #(id, bits) <- result_.try(case slots_to_fill > 0 {
        active if active -> id_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#("", bits))
      })
      use #(location_name, bits) <- result_.try(case slots_to_fill > 1 {
        active if active -> location_name_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#("", bits))
      })
      use #(expression, bits) <- result_.try(case slots_to_fill > 2 {
        active if active -> expression_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#("", bits))
      })
      Ok(#(InventoryRule(id:, location_name:, expression:, unrecognized_: struct_serializer_.None), bits))
    },
  )
}

// ==============================================================================
// struct InventoryRuleList
// ==============================================================================

pub type InventoryRuleList {
  InventoryRuleList(
    data: List(InventoryRule),
    total: Int,
    /// Stores unrecognized fields from newer schema versions for round-trip compatibility.
    /// Set this to `struct_serializer_.None` when creating values manually.
    unrecognized_: struct_serializer_.UnrecognizedFields(InventoryRuleList),
  )
}

/// The default `InventoryRuleList` with all fields set to their default values.
pub const inventory_rule_list_default = InventoryRuleList(
  data: [],
  total: 0,
  unrecognized_: struct_serializer_.None,
)

/// Creates a new `InventoryRuleList` with the given field values.
pub fn inventory_rule_list_new(
  data: List(InventoryRule),
  total: Int,
) -> InventoryRuleList {
  InventoryRuleList(
    data: data,
    total: total,
    unrecognized_: struct_serializer_.None,
  )
}

/// Returns the serializer for `InventoryRuleList` values.
pub fn inventory_rule_list_serializer() -> skir_client_.Serializer(InventoryRuleList) {
  let data_serializer = skir_client_.list_serializer(
    inventory_rule_serializer(),
  )
  let total_serializer = skir_client_.int32_serializer()
  struct_serializer_.new_serializer(
    name: "InventoryRuleList",
    qualified_name: "InventoryRuleList",
    module_path: "inventory_planning/queries.skir",
    doc: "",
    ordered_fields: [
      struct_serializer_.field_spec_to_field_adapter(
        name: "data",
        number: 0,
        doc: "",
        default: [],
        type_sig: type_descriptor_.Array(type_descriptor_.Record("inventory_planning/queries.skir:InventoryRule"), ""),
        get: fn(s: InventoryRuleList) { s.data },
        set: fn(s: InventoryRuleList, v: List(InventoryRule)) { InventoryRuleList(..s, data: v) },
        serializer: struct_serializer_.Eager(data_serializer),
      ),
      struct_serializer_.field_spec_to_field_adapter(
        name: "total",
        number: 1,
        doc: "",
        default: 0,
        type_sig: type_descriptor_.Primitive(type_descriptor_.Int32),
        get: fn(s: InventoryRuleList) { s.total },
        set: fn(s: InventoryRuleList, v: Int) { InventoryRuleList(..s, total: v) },
        serializer: struct_serializer_.Eager(total_serializer),
      ),
    ],
    default: inventory_rule_list_default,
    get_unrecognized: fn(s) { s.unrecognized_ },
    set_unrecognized: fn(s, u) { InventoryRuleList(..s, unrecognized_: u) },
    removed_numbers: [],
    recognized_slot_count: 2,
    decode_dense_json: fn(arr, keep) {
      use #(data, arr) <- result_.try(case arr {
        [] -> Ok(#([], []))
        [elem, ..arr] -> decode_.run(elem, data_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      use #(total, arr) <- result_.try(case arr {
        [] -> Ok(#(0, []))
        [elem, ..arr] -> decode_.run(elem, total_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      let unrecognized_ = struct_serializer_.make_unrecognized_fields_json(arr, list_.length(arr) + 2, keep)
      Ok(InventoryRuleList(data:, total:, unrecognized_:))
    },
    decode_binary: fn(bits, slots_to_fill, keep) {
      use #(data, bits) <- result_.try(case slots_to_fill > 0 {
        active if active -> data_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#([], bits))
      })
      use #(total, bits) <- result_.try(case slots_to_fill > 1 {
        active if active -> total_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#(0, bits))
      })
      Ok(#(InventoryRuleList(data:, total:, unrecognized_: struct_serializer_.None), bits))
    },
  )
}

// ==============================================================================
// struct ListInventoryRulesRequest
// ==============================================================================

pub type ListInventoryRulesRequest {
  ListInventoryRulesRequest(
    unit: Bool,
    /// Stores unrecognized fields from newer schema versions for round-trip compatibility.
    /// Set this to `struct_serializer_.None` when creating values manually.
    unrecognized_: struct_serializer_.UnrecognizedFields(ListInventoryRulesRequest),
  )
}

/// The default `ListInventoryRulesRequest` with all fields set to their default values.
pub const list_inventory_rules_request_default = ListInventoryRulesRequest(
  unit: False,
  unrecognized_: struct_serializer_.None,
)

/// Creates a new `ListInventoryRulesRequest` with the given field values.
pub fn list_inventory_rules_request_new(
  unit: Bool,
) -> ListInventoryRulesRequest {
  ListInventoryRulesRequest(
    unit: unit,
    unrecognized_: struct_serializer_.None,
  )
}

/// Returns the serializer for `ListInventoryRulesRequest` values.
pub fn list_inventory_rules_request_serializer() -> skir_client_.Serializer(ListInventoryRulesRequest) {
  let unit_serializer = skir_client_.bool_serializer()
  struct_serializer_.new_serializer(
    name: "ListInventoryRulesRequest",
    qualified_name: "ListInventoryRulesRequest",
    module_path: "inventory_planning/queries.skir",
    doc: "",
    ordered_fields: [
      struct_serializer_.field_spec_to_field_adapter(
        name: "unit",
        number: 0,
        doc: "",
        default: False,
        type_sig: type_descriptor_.Primitive(type_descriptor_.Bool),
        get: fn(s: ListInventoryRulesRequest) { s.unit },
        set: fn(s: ListInventoryRulesRequest, v: Bool) { ListInventoryRulesRequest(..s, unit: v) },
        serializer: struct_serializer_.Eager(unit_serializer),
      ),
    ],
    default: list_inventory_rules_request_default,
    get_unrecognized: fn(s) { s.unrecognized_ },
    set_unrecognized: fn(s, u) { ListInventoryRulesRequest(..s, unrecognized_: u) },
    removed_numbers: [],
    recognized_slot_count: 1,
    decode_dense_json: fn(arr, keep) {
      use #(unit, arr) <- result_.try(case arr {
        [] -> Ok(#(False, []))
        [elem, ..arr] -> decode_.run(elem, unit_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      let unrecognized_ = struct_serializer_.make_unrecognized_fields_json(arr, list_.length(arr) + 1, keep)
      Ok(ListInventoryRulesRequest(unit:, unrecognized_:))
    },
    decode_binary: fn(bits, slots_to_fill, keep) {
      use #(unit, bits) <- result_.try(case slots_to_fill > 0 {
        active if active -> unit_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#(False, bits))
      })
      Ok(#(ListInventoryRulesRequest(unit:, unrecognized_: struct_serializer_.None), bits))
    },
  )
}

// ==============================================================================
// struct InventoryProjectionRequest
// ==============================================================================

pub type InventoryProjectionRequest {
  InventoryProjectionRequest(
    group_by: String,
    sort_by: String,
    /// Stores unrecognized fields from newer schema versions for round-trip compatibility.
    /// Set this to `struct_serializer_.None` when creating values manually.
    unrecognized_: struct_serializer_.UnrecognizedFields(InventoryProjectionRequest),
  )
}

/// The default `InventoryProjectionRequest` with all fields set to their default values.
pub const inventory_projection_request_default = InventoryProjectionRequest(
  group_by: "",
  sort_by: "",
  unrecognized_: struct_serializer_.None,
)

/// Creates a new `InventoryProjectionRequest` with the given field values.
pub fn inventory_projection_request_new(
  group_by: String,
  sort_by: String,
) -> InventoryProjectionRequest {
  InventoryProjectionRequest(
    group_by: group_by,
    sort_by: sort_by,
    unrecognized_: struct_serializer_.None,
  )
}

/// Returns the serializer for `InventoryProjectionRequest` values.
pub fn inventory_projection_request_serializer() -> skir_client_.Serializer(InventoryProjectionRequest) {
  let sort_by_serializer = skir_client_.string_serializer()
  let group_by_serializer = skir_client_.string_serializer()
  struct_serializer_.new_serializer(
    name: "InventoryProjectionRequest",
    qualified_name: "InventoryProjectionRequest",
    module_path: "inventory_planning/queries.skir",
    doc: "",
    ordered_fields: [
      struct_serializer_.field_spec_to_field_adapter(
        name: "sort_by",
        number: 0,
        doc: "",
        default: "",
        type_sig: type_descriptor_.Primitive(type_descriptor_.StringType),
        get: fn(s: InventoryProjectionRequest) { s.sort_by },
        set: fn(s: InventoryProjectionRequest, v: String) { InventoryProjectionRequest(..s, sort_by: v) },
        serializer: struct_serializer_.Eager(sort_by_serializer),
      ),
      struct_serializer_.field_spec_to_field_adapter(
        name: "group_by",
        number: 1,
        doc: "",
        default: "",
        type_sig: type_descriptor_.Primitive(type_descriptor_.StringType),
        get: fn(s: InventoryProjectionRequest) { s.group_by },
        set: fn(s: InventoryProjectionRequest, v: String) { InventoryProjectionRequest(..s, group_by: v) },
        serializer: struct_serializer_.Eager(group_by_serializer),
      ),
    ],
    default: inventory_projection_request_default,
    get_unrecognized: fn(s) { s.unrecognized_ },
    set_unrecognized: fn(s, u) { InventoryProjectionRequest(..s, unrecognized_: u) },
    removed_numbers: [],
    recognized_slot_count: 2,
    decode_dense_json: fn(arr, keep) {
      use #(sort_by, arr) <- result_.try(case arr {
        [] -> Ok(#("", []))
        [elem, ..arr] -> decode_.run(elem, sort_by_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      use #(group_by, arr) <- result_.try(case arr {
        [] -> Ok(#("", []))
        [elem, ..arr] -> decode_.run(elem, group_by_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      let unrecognized_ = struct_serializer_.make_unrecognized_fields_json(arr, list_.length(arr) + 2, keep)
      Ok(InventoryProjectionRequest(sort_by:, group_by:, unrecognized_:))
    },
    decode_binary: fn(bits, slots_to_fill, keep) {
      use #(sort_by, bits) <- result_.try(case slots_to_fill > 0 {
        active if active -> sort_by_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#("", bits))
      })
      use #(group_by, bits) <- result_.try(case slots_to_fill > 1 {
        active if active -> group_by_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#("", bits))
      })
      Ok(#(InventoryProjectionRequest(sort_by:, group_by:, unrecognized_: struct_serializer_.None), bits))
    },
  )
}

// ==============================================================================
// struct InventoryProjectionRow
// ==============================================================================

pub type InventoryProjectionRow {
  InventoryProjectionRow(
    card_name: String,
    group_value: String,
    location_name: String,
    quantity: Int,
    set_code: String,
    /// Stores unrecognized fields from newer schema versions for round-trip compatibility.
    /// Set this to `struct_serializer_.None` when creating values manually.
    unrecognized_: struct_serializer_.UnrecognizedFields(InventoryProjectionRow),
  )
}

/// The default `InventoryProjectionRow` with all fields set to their default values.
pub const inventory_projection_row_default = InventoryProjectionRow(
  card_name: "",
  group_value: "",
  location_name: "",
  quantity: 0,
  set_code: "",
  unrecognized_: struct_serializer_.None,
)

/// Creates a new `InventoryProjectionRow` with the given field values.
pub fn inventory_projection_row_new(
  card_name: String,
  group_value: String,
  location_name: String,
  quantity: Int,
  set_code: String,
) -> InventoryProjectionRow {
  InventoryProjectionRow(
    card_name: card_name,
    group_value: group_value,
    location_name: location_name,
    quantity: quantity,
    set_code: set_code,
    unrecognized_: struct_serializer_.None,
  )
}

/// Returns the serializer for `InventoryProjectionRow` values.
pub fn inventory_projection_row_serializer() -> skir_client_.Serializer(InventoryProjectionRow) {
  let location_name_serializer = skir_client_.string_serializer()
  let card_name_serializer = skir_client_.string_serializer()
  let set_code_serializer = skir_client_.string_serializer()
  let quantity_serializer = skir_client_.int32_serializer()
  let group_value_serializer = skir_client_.string_serializer()
  struct_serializer_.new_serializer(
    name: "InventoryProjectionRow",
    qualified_name: "InventoryProjectionRow",
    module_path: "inventory_planning/queries.skir",
    doc: "",
    ordered_fields: [
      struct_serializer_.field_spec_to_field_adapter(
        name: "location_name",
        number: 0,
        doc: "",
        default: "",
        type_sig: type_descriptor_.Primitive(type_descriptor_.StringType),
        get: fn(s: InventoryProjectionRow) { s.location_name },
        set: fn(s: InventoryProjectionRow, v: String) { InventoryProjectionRow(..s, location_name: v) },
        serializer: struct_serializer_.Eager(location_name_serializer),
      ),
      struct_serializer_.field_spec_to_field_adapter(
        name: "card_name",
        number: 1,
        doc: "",
        default: "",
        type_sig: type_descriptor_.Primitive(type_descriptor_.StringType),
        get: fn(s: InventoryProjectionRow) { s.card_name },
        set: fn(s: InventoryProjectionRow, v: String) { InventoryProjectionRow(..s, card_name: v) },
        serializer: struct_serializer_.Eager(card_name_serializer),
      ),
      struct_serializer_.field_spec_to_field_adapter(
        name: "set_code",
        number: 2,
        doc: "",
        default: "",
        type_sig: type_descriptor_.Primitive(type_descriptor_.StringType),
        get: fn(s: InventoryProjectionRow) { s.set_code },
        set: fn(s: InventoryProjectionRow, v: String) { InventoryProjectionRow(..s, set_code: v) },
        serializer: struct_serializer_.Eager(set_code_serializer),
      ),
      struct_serializer_.field_spec_to_field_adapter(
        name: "quantity",
        number: 3,
        doc: "",
        default: 0,
        type_sig: type_descriptor_.Primitive(type_descriptor_.Int32),
        get: fn(s: InventoryProjectionRow) { s.quantity },
        set: fn(s: InventoryProjectionRow, v: Int) { InventoryProjectionRow(..s, quantity: v) },
        serializer: struct_serializer_.Eager(quantity_serializer),
      ),
      struct_serializer_.field_spec_to_field_adapter(
        name: "group_value",
        number: 4,
        doc: "",
        default: "",
        type_sig: type_descriptor_.Primitive(type_descriptor_.StringType),
        get: fn(s: InventoryProjectionRow) { s.group_value },
        set: fn(s: InventoryProjectionRow, v: String) { InventoryProjectionRow(..s, group_value: v) },
        serializer: struct_serializer_.Eager(group_value_serializer),
      ),
    ],
    default: inventory_projection_row_default,
    get_unrecognized: fn(s) { s.unrecognized_ },
    set_unrecognized: fn(s, u) { InventoryProjectionRow(..s, unrecognized_: u) },
    removed_numbers: [],
    recognized_slot_count: 5,
    decode_dense_json: fn(arr, keep) {
      use #(location_name, arr) <- result_.try(case arr {
        [] -> Ok(#("", []))
        [elem, ..arr] -> decode_.run(elem, location_name_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      use #(card_name, arr) <- result_.try(case arr {
        [] -> Ok(#("", []))
        [elem, ..arr] -> decode_.run(elem, card_name_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      use #(set_code, arr) <- result_.try(case arr {
        [] -> Ok(#("", []))
        [elem, ..arr] -> decode_.run(elem, set_code_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      use #(quantity, arr) <- result_.try(case arr {
        [] -> Ok(#(0, []))
        [elem, ..arr] -> decode_.run(elem, quantity_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      use #(group_value, arr) <- result_.try(case arr {
        [] -> Ok(#("", []))
        [elem, ..arr] -> decode_.run(elem, group_value_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      let unrecognized_ = struct_serializer_.make_unrecognized_fields_json(arr, list_.length(arr) + 5, keep)
      Ok(InventoryProjectionRow(location_name:, card_name:, set_code:, quantity:, group_value:, unrecognized_:))
    },
    decode_binary: fn(bits, slots_to_fill, keep) {
      use #(location_name, bits) <- result_.try(case slots_to_fill > 0 {
        active if active -> location_name_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#("", bits))
      })
      use #(card_name, bits) <- result_.try(case slots_to_fill > 1 {
        active if active -> card_name_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#("", bits))
      })
      use #(set_code, bits) <- result_.try(case slots_to_fill > 2 {
        active if active -> set_code_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#("", bits))
      })
      use #(quantity, bits) <- result_.try(case slots_to_fill > 3 {
        active if active -> quantity_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#(0, bits))
      })
      use #(group_value, bits) <- result_.try(case slots_to_fill > 4 {
        active if active -> group_value_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#("", bits))
      })
      Ok(#(InventoryProjectionRow(location_name:, card_name:, set_code:, quantity:, group_value:, unrecognized_: struct_serializer_.None), bits))
    },
  )
}

// ==============================================================================
// struct InventoryProjection
// ==============================================================================

pub type InventoryProjection {
  InventoryProjection(
    data: List(InventoryProjectionRow),
    total: Int,
    /// Stores unrecognized fields from newer schema versions for round-trip compatibility.
    /// Set this to `struct_serializer_.None` when creating values manually.
    unrecognized_: struct_serializer_.UnrecognizedFields(InventoryProjection),
  )
}

/// The default `InventoryProjection` with all fields set to their default values.
pub const inventory_projection_default = InventoryProjection(
  data: [],
  total: 0,
  unrecognized_: struct_serializer_.None,
)

/// Creates a new `InventoryProjection` with the given field values.
pub fn inventory_projection_new(
  data: List(InventoryProjectionRow),
  total: Int,
) -> InventoryProjection {
  InventoryProjection(
    data: data,
    total: total,
    unrecognized_: struct_serializer_.None,
  )
}

/// Returns the serializer for `InventoryProjection` values.
pub fn inventory_projection_serializer() -> skir_client_.Serializer(InventoryProjection) {
  let data_serializer = skir_client_.list_serializer(
    inventory_projection_row_serializer(),
  )
  let total_serializer = skir_client_.int32_serializer()
  struct_serializer_.new_serializer(
    name: "InventoryProjection",
    qualified_name: "InventoryProjection",
    module_path: "inventory_planning/queries.skir",
    doc: "",
    ordered_fields: [
      struct_serializer_.field_spec_to_field_adapter(
        name: "data",
        number: 0,
        doc: "",
        default: [],
        type_sig: type_descriptor_.Array(type_descriptor_.Record("inventory_planning/queries.skir:InventoryProjectionRow"), ""),
        get: fn(s: InventoryProjection) { s.data },
        set: fn(s: InventoryProjection, v: List(InventoryProjectionRow)) { InventoryProjection(..s, data: v) },
        serializer: struct_serializer_.Eager(data_serializer),
      ),
      struct_serializer_.field_spec_to_field_adapter(
        name: "total",
        number: 1,
        doc: "",
        default: 0,
        type_sig: type_descriptor_.Primitive(type_descriptor_.Int32),
        get: fn(s: InventoryProjection) { s.total },
        set: fn(s: InventoryProjection, v: Int) { InventoryProjection(..s, total: v) },
        serializer: struct_serializer_.Eager(total_serializer),
      ),
    ],
    default: inventory_projection_default,
    get_unrecognized: fn(s) { s.unrecognized_ },
    set_unrecognized: fn(s, u) { InventoryProjection(..s, unrecognized_: u) },
    removed_numbers: [],
    recognized_slot_count: 2,
    decode_dense_json: fn(arr, keep) {
      use #(data, arr) <- result_.try(case arr {
        [] -> Ok(#([], []))
        [elem, ..arr] -> decode_.run(elem, data_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      use #(total, arr) <- result_.try(case arr {
        [] -> Ok(#(0, []))
        [elem, ..arr] -> decode_.run(elem, total_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      let unrecognized_ = struct_serializer_.make_unrecognized_fields_json(arr, list_.length(arr) + 2, keep)
      Ok(InventoryProjection(data:, total:, unrecognized_:))
    },
    decode_binary: fn(bits, slots_to_fill, keep) {
      use #(data, bits) <- result_.try(case slots_to_fill > 0 {
        active if active -> data_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#([], bits))
      })
      use #(total, bits) <- result_.try(case slots_to_fill > 1 {
        active if active -> total_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#(0, bits))
      })
      Ok(#(InventoryProjection(data:, total:, unrecognized_: struct_serializer_.None), bits))
    },
  )
}

// ==============================================================================
// method ListInventoryRules
// ==============================================================================

pub fn list_inventory_rules_method() -> method_.Method(ListInventoryRulesRequest, InventoryRuleList) {
  method_.Method(
    name: "ListInventoryRules",
    number: 303,
    doc: "",
    request_serializer: list_inventory_rules_request_serializer(),
    response_serializer: inventory_rule_list_serializer(),
  )
}

// ==============================================================================
// method GetInventoryProjection
// ==============================================================================

pub fn get_inventory_projection_method() -> method_.Method(InventoryProjectionRequest, InventoryProjection) {
  method_.Method(
    name: "GetInventoryProjection",
    number: 304,
    doc: "",
    request_serializer: inventory_projection_request_serializer(),
    response_serializer: inventory_projection_serializer(),
  )
}
