name = "linting"
version = "1.0.0"
target = "erlang"

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
glinter = ">= 2.19.0 and < 3.0.0"
simplifile = ">= 2.4.0 and < 3.0.0"
glance = ">= 6.0.0 and < 7.0.0"
gleam_crypto = ">= 1.6.0 and < 2.0.0"
