//  ______                        _               _  _  _
//  |  _  \                      | |             | |(_)| |
//  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_
//  | | | | / _ \  | '_ \  / _ \ | __|  / _ \ / _` || || __|
//  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_
//  |___/   \___/  |_| |_| \___/  \__|  \___| \__,_||_| \__|
//
// Generated by skir-gleam-gen
// Home: https://github.com/gepheum/skir-gleam-gen
//
// To install the Skir client library, run:
//   gleam add skir_client
//
// Do not edit this file manually.

import gleam/dynamic/decode as decode_
import skir_client/method as method_
import skir_client as skir_client_
import skir_client/type_descriptor as type_descriptor_
import skir_client/internal/struct_serializer as struct_serializer_
import gleam/list as list_
import gleam/result as result_
import skir_client/internal/enum_serializer as enum_serializer_

// ==============================================================================
// struct ImportCollectionRow
// ==============================================================================

pub type ImportCollectionRow {
  ImportCollectionRow(
    card_name: String,
    collector_number: String,
    quantity: Int,
    set_code: String,
    /// Stores unrecognized fields from newer schema versions for round-trip compatibility.
    /// Set this to `struct_serializer_.None` when creating values manually.
    unrecognized_: struct_serializer_.UnrecognizedFields(ImportCollectionRow),
  )
}

/// The default `ImportCollectionRow` with all fields set to their default values.
pub const import_collection_row_default = ImportCollectionRow(
  card_name: "",
  collector_number: "",
  quantity: 0,
  set_code: "",
  unrecognized_: struct_serializer_.None,
)

/// Creates a new `ImportCollectionRow` with the given field values.
pub fn import_collection_row_new(
  card_name: String,
  collector_number: String,
  quantity: Int,
  set_code: String,
) -> ImportCollectionRow {
  ImportCollectionRow(
    card_name: card_name,
    collector_number: collector_number,
    quantity: quantity,
    set_code: set_code,
    unrecognized_: struct_serializer_.None,
  )
}

/// Returns the serializer for `ImportCollectionRow` values.
pub fn import_collection_row_serializer() -> skir_client_.Serializer(ImportCollectionRow) {
  let card_name_serializer = skir_client_.string_serializer()
  let set_code_serializer = skir_client_.string_serializer()
  let collector_number_serializer = skir_client_.string_serializer()
  let quantity_serializer = skir_client_.int32_serializer()
  struct_serializer_.new_serializer(
    name: "ImportCollectionRow",
    qualified_name: "ImportCollectionRow",
    module_path: "collection_import/commands.skir",
    doc: "",
    ordered_fields: [
      struct_serializer_.field_spec_to_field_adapter(
        name: "card_name",
        number: 0,
        doc: "",
        default: "",
        type_sig: type_descriptor_.Primitive(type_descriptor_.StringType),
        get: fn(s: ImportCollectionRow) { s.card_name },
        set: fn(s: ImportCollectionRow, v: String) { ImportCollectionRow(..s, card_name: v) },
        serializer: struct_serializer_.Eager(card_name_serializer),
      ),
      struct_serializer_.field_spec_to_field_adapter(
        name: "set_code",
        number: 1,
        doc: "",
        default: "",
        type_sig: type_descriptor_.Primitive(type_descriptor_.StringType),
        get: fn(s: ImportCollectionRow) { s.set_code },
        set: fn(s: ImportCollectionRow, v: String) { ImportCollectionRow(..s, set_code: v) },
        serializer: struct_serializer_.Eager(set_code_serializer),
      ),
      struct_serializer_.field_spec_to_field_adapter(
        name: "collector_number",
        number: 2,
        doc: "",
        default: "",
        type_sig: type_descriptor_.Primitive(type_descriptor_.StringType),
        get: fn(s: ImportCollectionRow) { s.collector_number },
        set: fn(s: ImportCollectionRow, v: String) { ImportCollectionRow(..s, collector_number: v) },
        serializer: struct_serializer_.Eager(collector_number_serializer),
      ),
      struct_serializer_.field_spec_to_field_adapter(
        name: "quantity",
        number: 3,
        doc: "",
        default: 0,
        type_sig: type_descriptor_.Primitive(type_descriptor_.Int32),
        get: fn(s: ImportCollectionRow) { s.quantity },
        set: fn(s: ImportCollectionRow, v: Int) { ImportCollectionRow(..s, quantity: v) },
        serializer: struct_serializer_.Eager(quantity_serializer),
      ),
    ],
    default: import_collection_row_default,
    get_unrecognized: fn(s) { s.unrecognized_ },
    set_unrecognized: fn(s, u) { ImportCollectionRow(..s, unrecognized_: u) },
    removed_numbers: [],
    recognized_slot_count: 4,
    decode_dense_json: fn(arr, keep) {
      use #(card_name, arr) <- result_.try(case arr {
        [] -> Ok(#("", []))
        [elem, ..arr] -> decode_.run(elem, card_name_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      use #(set_code, arr) <- result_.try(case arr {
        [] -> Ok(#("", []))
        [elem, ..arr] -> decode_.run(elem, set_code_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      use #(collector_number, arr) <- result_.try(case arr {
        [] -> Ok(#("", []))
        [elem, ..arr] -> decode_.run(elem, collector_number_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      use #(quantity, arr) <- result_.try(case arr {
        [] -> Ok(#(0, []))
        [elem, ..arr] -> decode_.run(elem, quantity_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      let unrecognized_ = struct_serializer_.make_unrecognized_fields_json(arr, list_.length(arr) + 4, keep)
      Ok(ImportCollectionRow(card_name:, set_code:, collector_number:, quantity:, unrecognized_:))
    },
    decode_binary: fn(bits, slots_to_fill, keep) {
      use #(card_name, bits) <- result_.try(case slots_to_fill > 0 {
        active if active -> card_name_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#("", bits))
      })
      use #(set_code, bits) <- result_.try(case slots_to_fill > 1 {
        active if active -> set_code_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#("", bits))
      })
      use #(collector_number, bits) <- result_.try(case slots_to_fill > 2 {
        active if active -> collector_number_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#("", bits))
      })
      use #(quantity, bits) <- result_.try(case slots_to_fill > 3 {
        active if active -> quantity_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#(0, bits))
      })
      Ok(#(ImportCollectionRow(card_name:, set_code:, collector_number:, quantity:, unrecognized_: struct_serializer_.None), bits))
    },
  )
}

// ==============================================================================
// struct ImportCollectionRequest
// ==============================================================================

pub type ImportCollectionRequest {
  ImportCollectionRequest(
    import_run_id: String,
    row_count: Int,
    rows: List(ImportCollectionRow),
    source_checksum: String,
    source_name: String,
    /// Stores unrecognized fields from newer schema versions for round-trip compatibility.
    /// Set this to `struct_serializer_.None` when creating values manually.
    unrecognized_: struct_serializer_.UnrecognizedFields(ImportCollectionRequest),
  )
}

/// The default `ImportCollectionRequest` with all fields set to their default values.
pub const import_collection_request_default = ImportCollectionRequest(
  import_run_id: "",
  row_count: 0,
  rows: [],
  source_checksum: "",
  source_name: "",
  unrecognized_: struct_serializer_.None,
)

/// Creates a new `ImportCollectionRequest` with the given field values.
pub fn import_collection_request_new(
  import_run_id: String,
  row_count: Int,
  rows: List(ImportCollectionRow),
  source_checksum: String,
  source_name: String,
) -> ImportCollectionRequest {
  ImportCollectionRequest(
    import_run_id: import_run_id,
    row_count: row_count,
    rows: rows,
    source_checksum: source_checksum,
    source_name: source_name,
    unrecognized_: struct_serializer_.None,
  )
}

/// Returns the serializer for `ImportCollectionRequest` values.
pub fn import_collection_request_serializer() -> skir_client_.Serializer(ImportCollectionRequest) {
  let import_run_id_serializer = skir_client_.string_serializer()
  let source_name_serializer = skir_client_.string_serializer()
  let source_checksum_serializer = skir_client_.string_serializer()
  let row_count_serializer = skir_client_.int32_serializer()
  let rows_serializer = skir_client_.list_serializer(
    import_collection_row_serializer(),
  )
  struct_serializer_.new_serializer(
    name: "ImportCollectionRequest",
    qualified_name: "ImportCollectionRequest",
    module_path: "collection_import/commands.skir",
    doc: "",
    ordered_fields: [
      struct_serializer_.field_spec_to_field_adapter(
        name: "import_run_id",
        number: 0,
        doc: "",
        default: "",
        type_sig: type_descriptor_.Primitive(type_descriptor_.StringType),
        get: fn(s: ImportCollectionRequest) { s.import_run_id },
        set: fn(s: ImportCollectionRequest, v: String) { ImportCollectionRequest(..s, import_run_id: v) },
        serializer: struct_serializer_.Eager(import_run_id_serializer),
      ),
      struct_serializer_.field_spec_to_field_adapter(
        name: "source_name",
        number: 1,
        doc: "",
        default: "",
        type_sig: type_descriptor_.Primitive(type_descriptor_.StringType),
        get: fn(s: ImportCollectionRequest) { s.source_name },
        set: fn(s: ImportCollectionRequest, v: String) { ImportCollectionRequest(..s, source_name: v) },
        serializer: struct_serializer_.Eager(source_name_serializer),
      ),
      struct_serializer_.field_spec_to_field_adapter(
        name: "source_checksum",
        number: 2,
        doc: "",
        default: "",
        type_sig: type_descriptor_.Primitive(type_descriptor_.StringType),
        get: fn(s: ImportCollectionRequest) { s.source_checksum },
        set: fn(s: ImportCollectionRequest, v: String) { ImportCollectionRequest(..s, source_checksum: v) },
        serializer: struct_serializer_.Eager(source_checksum_serializer),
      ),
      struct_serializer_.field_spec_to_field_adapter(
        name: "row_count",
        number: 3,
        doc: "",
        default: 0,
        type_sig: type_descriptor_.Primitive(type_descriptor_.Int32),
        get: fn(s: ImportCollectionRequest) { s.row_count },
        set: fn(s: ImportCollectionRequest, v: Int) { ImportCollectionRequest(..s, row_count: v) },
        serializer: struct_serializer_.Eager(row_count_serializer),
      ),
      struct_serializer_.field_spec_to_field_adapter(
        name: "rows",
        number: 4,
        doc: "",
        default: [],
        type_sig: type_descriptor_.Array(type_descriptor_.Record("collection_import/commands.skir:ImportCollectionRow"), ""),
        get: fn(s: ImportCollectionRequest) { s.rows },
        set: fn(s: ImportCollectionRequest, v: List(ImportCollectionRow)) { ImportCollectionRequest(..s, rows: v) },
        serializer: struct_serializer_.Eager(rows_serializer),
      ),
    ],
    default: import_collection_request_default,
    get_unrecognized: fn(s) { s.unrecognized_ },
    set_unrecognized: fn(s, u) { ImportCollectionRequest(..s, unrecognized_: u) },
    removed_numbers: [],
    recognized_slot_count: 5,
    decode_dense_json: fn(arr, keep) {
      use #(import_run_id, arr) <- result_.try(case arr {
        [] -> Ok(#("", []))
        [elem, ..arr] -> decode_.run(elem, import_run_id_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      use #(source_name, arr) <- result_.try(case arr {
        [] -> Ok(#("", []))
        [elem, ..arr] -> decode_.run(elem, source_name_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      use #(source_checksum, arr) <- result_.try(case arr {
        [] -> Ok(#("", []))
        [elem, ..arr] -> decode_.run(elem, source_checksum_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      use #(row_count, arr) <- result_.try(case arr {
        [] -> Ok(#(0, []))
        [elem, ..arr] -> decode_.run(elem, row_count_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      use #(rows, arr) <- result_.try(case arr {
        [] -> Ok(#([], []))
        [elem, ..arr] -> decode_.run(elem, rows_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      let unrecognized_ = struct_serializer_.make_unrecognized_fields_json(arr, list_.length(arr) + 5, keep)
      Ok(ImportCollectionRequest(import_run_id:, source_name:, source_checksum:, row_count:, rows:, unrecognized_:))
    },
    decode_binary: fn(bits, slots_to_fill, keep) {
      use #(import_run_id, bits) <- result_.try(case slots_to_fill > 0 {
        active if active -> import_run_id_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#("", bits))
      })
      use #(source_name, bits) <- result_.try(case slots_to_fill > 1 {
        active if active -> source_name_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#("", bits))
      })
      use #(source_checksum, bits) <- result_.try(case slots_to_fill > 2 {
        active if active -> source_checksum_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#("", bits))
      })
      use #(row_count, bits) <- result_.try(case slots_to_fill > 3 {
        active if active -> row_count_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#(0, bits))
      })
      use #(rows, bits) <- result_.try(case slots_to_fill > 4 {
        active if active -> rows_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#([], bits))
      })
      Ok(#(ImportCollectionRequest(import_run_id:, source_name:, source_checksum:, row_count:, rows:, unrecognized_: struct_serializer_.None), bits))
    },
  )
}

// ==============================================================================
// enum ImportCollectionResponse
// ==============================================================================

pub type ImportCollectionResponse {
  ImportCollectionResponseUnknown(enum_serializer_.UnrecognizedVariant(ImportCollectionResponse))
  ImportCollectionResponseAccepted
  ImportCollectionResponseRejected
}

/// The default `ImportCollectionResponse` (the unknown variant).
pub const import_collection_response_unknown = ImportCollectionResponseUnknown(enum_serializer_.None)

/// Returns the serializer for `ImportCollectionResponse` values.
pub fn import_collection_response_serializer() -> skir_client_.Serializer(ImportCollectionResponse) {
  enum_serializer_.new_serializer(
    name: "ImportCollectionResponse",
    qualified_name: "ImportCollectionResponse",
    module_path: "collection_import/commands.skir",
    doc: "",
    variants: [
      enum_serializer_.constant_variant(
        name: "accepted",
        number: 1,
        doc: "",
        instance: ImportCollectionResponseAccepted,
      ),
      enum_serializer_.constant_variant(
        name: "rejected",
        number: 2,
        doc: "",
        instance: ImportCollectionResponseRejected,
      ),
    ],
    unknown_default: import_collection_response_unknown,
    get_kind_ordinal: fn(e) {
      case e {
        ImportCollectionResponseUnknown(_) -> 0
        ImportCollectionResponseAccepted -> 1
        ImportCollectionResponseRejected -> 2
      }
    },
    wrap_unrecognized: fn(u) { ImportCollectionResponseUnknown(u) },
    get_unrecognized: fn(e) {
      case e {
        ImportCollectionResponseUnknown(u) -> u
        _ -> enum_serializer_.None
      }
    },
    removed_numbers: [],
  )
}

// ==============================================================================
// method ImportCollection
// ==============================================================================

pub fn import_collection_method() -> method_.Method(ImportCollectionRequest, ImportCollectionResponse) {
  method_.Method(
    name: "ImportCollection",
    number: 201,
    doc: "",
    request_serializer: import_collection_request_serializer(),
    response_serializer: import_collection_response_serializer(),
  )
}
