//  ______                        _               _  _  _
//  |  _  \                      | |             | |(_)| |
//  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_
//  | | | | / _ \  | '_ \  / _ \ | __|  / _ \ / _` || || __|
//  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_
//  |___/   \___/  |_| |_| \___/  \__|  \___| \__,_||_| \__|
//
// Generated by skir-gleam-gen
// Home: https://github.com/gepheum/skir-gleam-gen
//
// To install the Skir client library, run:
//   gleam add skir_client
//
// Do not edit this file manually.

import gleam/dynamic/decode as decode_
import skir_client/method as method_
import skir_client as skir_client_
import skir_client/type_descriptor as type_descriptor_
import skir_client/internal/struct_serializer as struct_serializer_
import gleam/list as list_
import gleam/result as result_

// ==============================================================================
// struct ImportStatus
// ==============================================================================

pub type ImportStatus {
  ImportStatus(
    import_run_id: String,
    row_count: Int,
    source_name: String,
    status: String,
    /// Stores unrecognized fields from newer schema versions for round-trip compatibility.
    /// Set this to `struct_serializer_.None` when creating values manually.
    unrecognized_: struct_serializer_.UnrecognizedFields(ImportStatus),
  )
}

/// The default `ImportStatus` with all fields set to their default values.
pub const import_status_default = ImportStatus(
  import_run_id: "",
  row_count: 0,
  source_name: "",
  status: "",
  unrecognized_: struct_serializer_.None,
)

/// Creates a new `ImportStatus` with the given field values.
pub fn import_status_new(
  import_run_id: String,
  row_count: Int,
  source_name: String,
  status: String,
) -> ImportStatus {
  ImportStatus(
    import_run_id: import_run_id,
    row_count: row_count,
    source_name: source_name,
    status: status,
    unrecognized_: struct_serializer_.None,
  )
}

/// Returns the serializer for `ImportStatus` values.
pub fn import_status_serializer() -> skir_client_.Serializer(ImportStatus) {
  let import_run_id_serializer = skir_client_.string_serializer()
  let status_serializer = skir_client_.string_serializer()
  let row_count_serializer = skir_client_.int32_serializer()
  let source_name_serializer = skir_client_.string_serializer()
  struct_serializer_.new_serializer(
    name: "ImportStatus",
    qualified_name: "ImportStatus",
    module_path: "collection_import/queries.skir",
    doc: "",
    ordered_fields: [
      struct_serializer_.field_spec_to_field_adapter(
        name: "import_run_id",
        number: 0,
        doc: "",
        default: "",
        type_sig: type_descriptor_.Primitive(type_descriptor_.StringType),
        get: fn(s: ImportStatus) { s.import_run_id },
        set: fn(s: ImportStatus, v: String) { ImportStatus(..s, import_run_id: v) },
        serializer: struct_serializer_.Eager(import_run_id_serializer),
      ),
      struct_serializer_.field_spec_to_field_adapter(
        name: "status",
        number: 1,
        doc: "",
        default: "",
        type_sig: type_descriptor_.Primitive(type_descriptor_.StringType),
        get: fn(s: ImportStatus) { s.status },
        set: fn(s: ImportStatus, v: String) { ImportStatus(..s, status: v) },
        serializer: struct_serializer_.Eager(status_serializer),
      ),
      struct_serializer_.field_spec_to_field_adapter(
        name: "row_count",
        number: 2,
        doc: "",
        default: 0,
        type_sig: type_descriptor_.Primitive(type_descriptor_.Int32),
        get: fn(s: ImportStatus) { s.row_count },
        set: fn(s: ImportStatus, v: Int) { ImportStatus(..s, row_count: v) },
        serializer: struct_serializer_.Eager(row_count_serializer),
      ),
      struct_serializer_.field_spec_to_field_adapter(
        name: "source_name",
        number: 3,
        doc: "",
        default: "",
        type_sig: type_descriptor_.Primitive(type_descriptor_.StringType),
        get: fn(s: ImportStatus) { s.source_name },
        set: fn(s: ImportStatus, v: String) { ImportStatus(..s, source_name: v) },
        serializer: struct_serializer_.Eager(source_name_serializer),
      ),
    ],
    default: import_status_default,
    get_unrecognized: fn(s) { s.unrecognized_ },
    set_unrecognized: fn(s, u) { ImportStatus(..s, unrecognized_: u) },
    removed_numbers: [],
    recognized_slot_count: 4,
    decode_dense_json: fn(arr, keep) {
      use #(import_run_id, arr) <- result_.try(case arr {
        [] -> Ok(#("", []))
        [elem, ..arr] -> decode_.run(elem, import_run_id_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      use #(status, arr) <- result_.try(case arr {
        [] -> Ok(#("", []))
        [elem, ..arr] -> decode_.run(elem, status_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      use #(row_count, arr) <- result_.try(case arr {
        [] -> Ok(#(0, []))
        [elem, ..arr] -> decode_.run(elem, row_count_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      use #(source_name, arr) <- result_.try(case arr {
        [] -> Ok(#("", []))
        [elem, ..arr] -> decode_.run(elem, source_name_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      let unrecognized_ = struct_serializer_.make_unrecognized_fields_json(arr, list_.length(arr) + 4, keep)
      Ok(ImportStatus(import_run_id:, status:, row_count:, source_name:, unrecognized_:))
    },
    decode_binary: fn(bits, slots_to_fill, keep) {
      use #(import_run_id, bits) <- result_.try(case slots_to_fill > 0 {
        active if active -> import_run_id_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#("", bits))
      })
      use #(status, bits) <- result_.try(case slots_to_fill > 1 {
        active if active -> status_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#("", bits))
      })
      use #(row_count, bits) <- result_.try(case slots_to_fill > 2 {
        active if active -> row_count_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#(0, bits))
      })
      use #(source_name, bits) <- result_.try(case slots_to_fill > 3 {
        active if active -> source_name_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#("", bits))
      })
      Ok(#(ImportStatus(import_run_id:, status:, row_count:, source_name:, unrecognized_: struct_serializer_.None), bits))
    },
  )
}

// ==============================================================================
// struct GetLatestImportStatusRequest
// ==============================================================================

pub type GetLatestImportStatusRequest {
  GetLatestImportStatusRequest(
    unit: Bool,
    /// Stores unrecognized fields from newer schema versions for round-trip compatibility.
    /// Set this to `struct_serializer_.None` when creating values manually.
    unrecognized_: struct_serializer_.UnrecognizedFields(GetLatestImportStatusRequest),
  )
}

/// The default `GetLatestImportStatusRequest` with all fields set to their default values.
pub const get_latest_import_status_request_default = GetLatestImportStatusRequest(
  unit: False,
  unrecognized_: struct_serializer_.None,
)

/// Creates a new `GetLatestImportStatusRequest` with the given field values.
pub fn get_latest_import_status_request_new(
  unit: Bool,
) -> GetLatestImportStatusRequest {
  GetLatestImportStatusRequest(
    unit: unit,
    unrecognized_: struct_serializer_.None,
  )
}

/// Returns the serializer for `GetLatestImportStatusRequest` values.
pub fn get_latest_import_status_request_serializer() -> skir_client_.Serializer(GetLatestImportStatusRequest) {
  let unit_serializer = skir_client_.bool_serializer()
  struct_serializer_.new_serializer(
    name: "GetLatestImportStatusRequest",
    qualified_name: "GetLatestImportStatusRequest",
    module_path: "collection_import/queries.skir",
    doc: "",
    ordered_fields: [
      struct_serializer_.field_spec_to_field_adapter(
        name: "unit",
        number: 0,
        doc: "",
        default: False,
        type_sig: type_descriptor_.Primitive(type_descriptor_.Bool),
        get: fn(s: GetLatestImportStatusRequest) { s.unit },
        set: fn(s: GetLatestImportStatusRequest, v: Bool) { GetLatestImportStatusRequest(..s, unit: v) },
        serializer: struct_serializer_.Eager(unit_serializer),
      ),
    ],
    default: get_latest_import_status_request_default,
    get_unrecognized: fn(s) { s.unrecognized_ },
    set_unrecognized: fn(s, u) { GetLatestImportStatusRequest(..s, unrecognized_: u) },
    removed_numbers: [],
    recognized_slot_count: 1,
    decode_dense_json: fn(arr, keep) {
      use #(unit, arr) <- result_.try(case arr {
        [] -> Ok(#(False, []))
        [elem, ..arr] -> decode_.run(elem, unit_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      let unrecognized_ = struct_serializer_.make_unrecognized_fields_json(arr, list_.length(arr) + 1, keep)
      Ok(GetLatestImportStatusRequest(unit:, unrecognized_:))
    },
    decode_binary: fn(bits, slots_to_fill, keep) {
      use #(unit, bits) <- result_.try(case slots_to_fill > 0 {
        active if active -> unit_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#(False, bits))
      })
      Ok(#(GetLatestImportStatusRequest(unit:, unrecognized_: struct_serializer_.None), bits))
    },
  )
}

// ==============================================================================
// method GetLatestImportStatus
// ==============================================================================

pub fn get_latest_import_status_method() -> method_.Method(GetLatestImportStatusRequest, ImportStatus) {
  method_.Method(
    name: "GetLatestImportStatus",
    number: 202,
    doc: "",
    request_serializer: get_latest_import_status_request_serializer(),
    response_serializer: import_status_serializer(),
  )
}
