//  ______                        _               _  _  _
//  |  _  \                      | |             | |(_)| |
//  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_
//  | | | | / _ \  | '_ \  / _ \ | __|  / _ \ / _` || || __|
//  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_
//  |___/   \___/  |_| |_| \___/  \__|  \___| \__,_||_| \__|
//
// Generated by skir-gleam-gen
// Home: https://github.com/gepheum/skir-gleam-gen
//
// To install the Skir client library, run:
//   gleam add skir_client
//
// Do not edit this file manually.

import gleam/dynamic/decode as decode_
import gleam/list as list_
import gleam/result as result_
import skir_client as skir_client_
import skir_client/internal/enum_serializer as enum_serializer_
import skir_client/internal/struct_serializer as struct_serializer_
import skir_client/method as method_
import skir_client/type_descriptor as type_descriptor_

// ==============================================================================
// struct RefreshCatalogRequest
// ==============================================================================

pub type RefreshCatalogRequest {
  RefreshCatalogRequest(
    unit: Bool,
    /// Stores unrecognized fields from newer schema versions for round-trip compatibility.
    /// Set this to `struct_serializer_.None` when creating values manually.
    unrecognized_: struct_serializer_.UnrecognizedFields(RefreshCatalogRequest),
  )
}

/// The default `RefreshCatalogRequest` with all fields set to their default values.
pub const refresh_catalog_request_default = RefreshCatalogRequest(
  unit: False,
  unrecognized_: struct_serializer_.None,
)

/// Creates a new `RefreshCatalogRequest` with the given field values.
pub fn refresh_catalog_request_new(unit: Bool) -> RefreshCatalogRequest {
  RefreshCatalogRequest(unit: unit, unrecognized_: struct_serializer_.None)
}

/// Returns the serializer for `RefreshCatalogRequest` values.
pub fn refresh_catalog_request_serializer() -> skir_client_.Serializer(
  RefreshCatalogRequest,
) {
  let unit_serializer = skir_client_.bool_serializer()
  struct_serializer_.new_serializer(
    name: "RefreshCatalogRequest",
    qualified_name: "RefreshCatalogRequest",
    module_path: "card_catalog/commands.skir",
    doc: "",
    ordered_fields: [
      struct_serializer_.field_spec_to_field_adapter(
        name: "unit",
        number: 0,
        doc: "",
        default: False,
        type_sig: type_descriptor_.Primitive(type_descriptor_.Bool),
        get: fn(s: RefreshCatalogRequest) { s.unit },
        set: fn(s: RefreshCatalogRequest, v: Bool) {
          RefreshCatalogRequest(..s, unit: v)
        },
        serializer: struct_serializer_.Eager(unit_serializer),
      ),
    ],
    default: refresh_catalog_request_default,
    get_unrecognized: fn(s) { s.unrecognized_ },
    set_unrecognized: fn(s, u) { RefreshCatalogRequest(..s, unrecognized_: u) },
    removed_numbers: [],
    recognized_slot_count: 1,
    decode_dense_json: fn(arr, keep) {
      use #(unit, arr) <- result_.try(case arr {
        [] -> Ok(#(False, []))
        [elem, ..arr] ->
          decode_.run(elem, unit_serializer.internal_adapter.decode_json(keep))
          |> result_.map(fn(v) { #(v, arr) })
      })
      let unrecognized_ =
        struct_serializer_.make_unrecognized_fields_json(
          arr,
          list_.length(arr) + 1,
          keep,
        )
      Ok(RefreshCatalogRequest(unit:, unrecognized_:))
    },
    decode_binary: fn(bits, slots_to_fill, keep) {
      use #(unit, bits) <- result_.try(case slots_to_fill > 0 {
        active if active -> unit_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#(False, bits))
      })
      Ok(#(
        RefreshCatalogRequest(unit:, unrecognized_: struct_serializer_.None),
        bits,
      ))
    },
  )
}

// ==============================================================================
// enum RefreshCatalogResponse
// ==============================================================================

pub type RefreshCatalogResponse {
  RefreshCatalogResponseUnknown(
    enum_serializer_.UnrecognizedVariant(RefreshCatalogResponse),
  )
  RefreshCatalogResponseSuccess
  RefreshCatalogResponseError
}

/// The default `RefreshCatalogResponse` (the unknown variant).
pub const refresh_catalog_response_unknown = RefreshCatalogResponseUnknown(
  enum_serializer_.None,
)

/// Returns the serializer for `RefreshCatalogResponse` values.
pub fn refresh_catalog_response_serializer() -> skir_client_.Serializer(
  RefreshCatalogResponse,
) {
  enum_serializer_.new_serializer(
    name: "RefreshCatalogResponse",
    qualified_name: "RefreshCatalogResponse",
    module_path: "card_catalog/commands.skir",
    doc: "",
    variants: [
      enum_serializer_.constant_variant(
        name: "success",
        number: 1,
        doc: "",
        instance: RefreshCatalogResponseSuccess,
      ),
      enum_serializer_.constant_variant(
        name: "error",
        number: 2,
        doc: "",
        instance: RefreshCatalogResponseError,
      ),
    ],
    unknown_default: refresh_catalog_response_unknown,
    get_kind_ordinal: fn(e) {
      case e {
        RefreshCatalogResponseUnknown(_) -> 0
        RefreshCatalogResponseSuccess -> 1
        RefreshCatalogResponseError -> 2
      }
    },
    wrap_unrecognized: fn(u) { RefreshCatalogResponseUnknown(u) },
    get_unrecognized: fn(e) {
      case e {
        RefreshCatalogResponseUnknown(u) -> u
        _ -> enum_serializer_.None
      }
    },
    removed_numbers: [],
  )
}

// ==============================================================================
// method RefreshCatalog
// ==============================================================================

pub fn refresh_catalog_method() -> method_.Method(
  RefreshCatalogRequest,
  RefreshCatalogResponse,
) {
  method_.Method(
    name: "RefreshCatalog",
    number: 101,
    doc: "",
    request_serializer: refresh_catalog_request_serializer(),
    response_serializer: refresh_catalog_response_serializer(),
  )
}
