//  ______                        _               _  _  _
//  |  _  \                      | |             | |(_)| |
//  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_
//  | | | | / _ \  | '_ \  / _ \ | __|  / _ \ / _` || || __|
//  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_
//  |___/   \___/  |_| |_| \___/  \__|  \___| \__,_||_| \__|
//
// Generated by skir-gleam-gen
// Home: https://github.com/gepheum/skir-gleam-gen
//
// To install the Skir client library, run:
//   gleam add skir_client
//
// Do not edit this file manually.

import gleam/dynamic/decode as decode_
import skir_client/method as method_
import skir_client as skir_client_
import skir_client/type_descriptor as type_descriptor_
import skir_client/internal/struct_serializer as struct_serializer_
import gleam/list as list_
import gleam/result as result_

// ==============================================================================
// struct CatalogCard
// ==============================================================================

pub type CatalogCard {
  CatalogCard(
    id: String,
    name: String,
    set_code: String,
    /// Stores unrecognized fields from newer schema versions for round-trip compatibility.
    /// Set this to `struct_serializer_.None` when creating values manually.
    unrecognized_: struct_serializer_.UnrecognizedFields(CatalogCard),
  )
}

/// The default `CatalogCard` with all fields set to their default values.
pub const catalog_card_default = CatalogCard(
  id: "",
  name: "",
  set_code: "",
  unrecognized_: struct_serializer_.None,
)

/// Creates a new `CatalogCard` with the given field values.
pub fn catalog_card_new(
  id: String,
  name: String,
  set_code: String,
) -> CatalogCard {
  CatalogCard(
    id: id,
    name: name,
    set_code: set_code,
    unrecognized_: struct_serializer_.None,
  )
}

/// Returns the serializer for `CatalogCard` values.
pub fn catalog_card_serializer() -> skir_client_.Serializer(CatalogCard) {
  let id_serializer = skir_client_.string_serializer()
  let name_serializer = skir_client_.string_serializer()
  let set_code_serializer = skir_client_.string_serializer()
  struct_serializer_.new_serializer(
    name: "CatalogCard",
    qualified_name: "CatalogCard",
    module_path: "card_catalog/queries.skir",
    doc: "",
    ordered_fields: [
      struct_serializer_.field_spec_to_field_adapter(
        name: "id",
        number: 0,
        doc: "",
        default: "",
        type_sig: type_descriptor_.Primitive(type_descriptor_.StringType),
        get: fn(s: CatalogCard) { s.id },
        set: fn(s: CatalogCard, v: String) { CatalogCard(..s, id: v) },
        serializer: struct_serializer_.Eager(id_serializer),
      ),
      struct_serializer_.field_spec_to_field_adapter(
        name: "name",
        number: 1,
        doc: "",
        default: "",
        type_sig: type_descriptor_.Primitive(type_descriptor_.StringType),
        get: fn(s: CatalogCard) { s.name },
        set: fn(s: CatalogCard, v: String) { CatalogCard(..s, name: v) },
        serializer: struct_serializer_.Eager(name_serializer),
      ),
      struct_serializer_.field_spec_to_field_adapter(
        name: "set_code",
        number: 2,
        doc: "",
        default: "",
        type_sig: type_descriptor_.Primitive(type_descriptor_.StringType),
        get: fn(s: CatalogCard) { s.set_code },
        set: fn(s: CatalogCard, v: String) { CatalogCard(..s, set_code: v) },
        serializer: struct_serializer_.Eager(set_code_serializer),
      ),
    ],
    default: catalog_card_default,
    get_unrecognized: fn(s) { s.unrecognized_ },
    set_unrecognized: fn(s, u) { CatalogCard(..s, unrecognized_: u) },
    removed_numbers: [],
    recognized_slot_count: 3,
    decode_dense_json: fn(arr, keep) {
      use #(id, arr) <- result_.try(case arr {
        [] -> Ok(#("", []))
        [elem, ..arr] -> decode_.run(elem, id_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      use #(name, arr) <- result_.try(case arr {
        [] -> Ok(#("", []))
        [elem, ..arr] -> decode_.run(elem, name_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      use #(set_code, arr) <- result_.try(case arr {
        [] -> Ok(#("", []))
        [elem, ..arr] -> decode_.run(elem, set_code_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      let unrecognized_ = struct_serializer_.make_unrecognized_fields_json(arr, list_.length(arr) + 3, keep)
      Ok(CatalogCard(id:, name:, set_code:, unrecognized_:))
    },
    decode_binary: fn(bits, slots_to_fill, keep) {
      use #(id, bits) <- result_.try(case slots_to_fill > 0 {
        active if active -> id_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#("", bits))
      })
      use #(name, bits) <- result_.try(case slots_to_fill > 1 {
        active if active -> name_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#("", bits))
      })
      use #(set_code, bits) <- result_.try(case slots_to_fill > 2 {
        active if active -> set_code_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#("", bits))
      })
      Ok(#(CatalogCard(id:, name:, set_code:, unrecognized_: struct_serializer_.None), bits))
    },
  )
}

// ==============================================================================
// struct CatalogCardList
// ==============================================================================

pub type CatalogCardList {
  CatalogCardList(
    data: List(CatalogCard),
    limit: Int,
    offset: Int,
    total: Int,
    /// Stores unrecognized fields from newer schema versions for round-trip compatibility.
    /// Set this to `struct_serializer_.None` when creating values manually.
    unrecognized_: struct_serializer_.UnrecognizedFields(CatalogCardList),
  )
}

/// The default `CatalogCardList` with all fields set to their default values.
pub const catalog_card_list_default = CatalogCardList(
  data: [],
  limit: 0,
  offset: 0,
  total: 0,
  unrecognized_: struct_serializer_.None,
)

/// Creates a new `CatalogCardList` with the given field values.
pub fn catalog_card_list_new(
  data: List(CatalogCard),
  limit: Int,
  offset: Int,
  total: Int,
) -> CatalogCardList {
  CatalogCardList(
    data: data,
    limit: limit,
    offset: offset,
    total: total,
    unrecognized_: struct_serializer_.None,
  )
}

/// Returns the serializer for `CatalogCardList` values.
pub fn catalog_card_list_serializer() -> skir_client_.Serializer(CatalogCardList) {
  let data_serializer = skir_client_.list_serializer(
    catalog_card_serializer(),
  )
  let total_serializer = skir_client_.int32_serializer()
  let offset_serializer = skir_client_.int32_serializer()
  let limit_serializer = skir_client_.int32_serializer()
  struct_serializer_.new_serializer(
    name: "CatalogCardList",
    qualified_name: "CatalogCardList",
    module_path: "card_catalog/queries.skir",
    doc: "",
    ordered_fields: [
      struct_serializer_.field_spec_to_field_adapter(
        name: "data",
        number: 0,
        doc: "",
        default: [],
        type_sig: type_descriptor_.Array(type_descriptor_.Record("card_catalog/queries.skir:CatalogCard"), ""),
        get: fn(s: CatalogCardList) { s.data },
        set: fn(s: CatalogCardList, v: List(CatalogCard)) { CatalogCardList(..s, data: v) },
        serializer: struct_serializer_.Eager(data_serializer),
      ),
      struct_serializer_.field_spec_to_field_adapter(
        name: "total",
        number: 1,
        doc: "",
        default: 0,
        type_sig: type_descriptor_.Primitive(type_descriptor_.Int32),
        get: fn(s: CatalogCardList) { s.total },
        set: fn(s: CatalogCardList, v: Int) { CatalogCardList(..s, total: v) },
        serializer: struct_serializer_.Eager(total_serializer),
      ),
      struct_serializer_.field_spec_to_field_adapter(
        name: "offset",
        number: 2,
        doc: "",
        default: 0,
        type_sig: type_descriptor_.Primitive(type_descriptor_.Int32),
        get: fn(s: CatalogCardList) { s.offset },
        set: fn(s: CatalogCardList, v: Int) { CatalogCardList(..s, offset: v) },
        serializer: struct_serializer_.Eager(offset_serializer),
      ),
      struct_serializer_.field_spec_to_field_adapter(
        name: "limit",
        number: 3,
        doc: "",
        default: 0,
        type_sig: type_descriptor_.Primitive(type_descriptor_.Int32),
        get: fn(s: CatalogCardList) { s.limit },
        set: fn(s: CatalogCardList, v: Int) { CatalogCardList(..s, limit: v) },
        serializer: struct_serializer_.Eager(limit_serializer),
      ),
    ],
    default: catalog_card_list_default,
    get_unrecognized: fn(s) { s.unrecognized_ },
    set_unrecognized: fn(s, u) { CatalogCardList(..s, unrecognized_: u) },
    removed_numbers: [],
    recognized_slot_count: 4,
    decode_dense_json: fn(arr, keep) {
      use #(data, arr) <- result_.try(case arr {
        [] -> Ok(#([], []))
        [elem, ..arr] -> decode_.run(elem, data_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      use #(total, arr) <- result_.try(case arr {
        [] -> Ok(#(0, []))
        [elem, ..arr] -> decode_.run(elem, total_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      use #(offset, arr) <- result_.try(case arr {
        [] -> Ok(#(0, []))
        [elem, ..arr] -> decode_.run(elem, offset_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      use #(limit, arr) <- result_.try(case arr {
        [] -> Ok(#(0, []))
        [elem, ..arr] -> decode_.run(elem, limit_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      let unrecognized_ = struct_serializer_.make_unrecognized_fields_json(arr, list_.length(arr) + 4, keep)
      Ok(CatalogCardList(data:, total:, offset:, limit:, unrecognized_:))
    },
    decode_binary: fn(bits, slots_to_fill, keep) {
      use #(data, bits) <- result_.try(case slots_to_fill > 0 {
        active if active -> data_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#([], bits))
      })
      use #(total, bits) <- result_.try(case slots_to_fill > 1 {
        active if active -> total_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#(0, bits))
      })
      use #(offset, bits) <- result_.try(case slots_to_fill > 2 {
        active if active -> offset_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#(0, bits))
      })
      use #(limit, bits) <- result_.try(case slots_to_fill > 3 {
        active if active -> limit_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#(0, bits))
      })
      Ok(#(CatalogCardList(data:, total:, offset:, limit:, unrecognized_: struct_serializer_.None), bits))
    },
  )
}

// ==============================================================================
// struct ListCatalogCardsRequest
// ==============================================================================

pub type ListCatalogCardsRequest {
  ListCatalogCardsRequest(
    limit: Int,
    offset: Int,
    /// Stores unrecognized fields from newer schema versions for round-trip compatibility.
    /// Set this to `struct_serializer_.None` when creating values manually.
    unrecognized_: struct_serializer_.UnrecognizedFields(ListCatalogCardsRequest),
  )
}

/// The default `ListCatalogCardsRequest` with all fields set to their default values.
pub const list_catalog_cards_request_default = ListCatalogCardsRequest(
  limit: 0,
  offset: 0,
  unrecognized_: struct_serializer_.None,
)

/// Creates a new `ListCatalogCardsRequest` with the given field values.
pub fn list_catalog_cards_request_new(
  limit: Int,
  offset: Int,
) -> ListCatalogCardsRequest {
  ListCatalogCardsRequest(
    limit: limit,
    offset: offset,
    unrecognized_: struct_serializer_.None,
  )
}

/// Returns the serializer for `ListCatalogCardsRequest` values.
pub fn list_catalog_cards_request_serializer() -> skir_client_.Serializer(ListCatalogCardsRequest) {
  let offset_serializer = skir_client_.int32_serializer()
  let limit_serializer = skir_client_.int32_serializer()
  struct_serializer_.new_serializer(
    name: "ListCatalogCardsRequest",
    qualified_name: "ListCatalogCardsRequest",
    module_path: "card_catalog/queries.skir",
    doc: "",
    ordered_fields: [
      struct_serializer_.field_spec_to_field_adapter(
        name: "offset",
        number: 0,
        doc: "",
        default: 0,
        type_sig: type_descriptor_.Primitive(type_descriptor_.Int32),
        get: fn(s: ListCatalogCardsRequest) { s.offset },
        set: fn(s: ListCatalogCardsRequest, v: Int) { ListCatalogCardsRequest(..s, offset: v) },
        serializer: struct_serializer_.Eager(offset_serializer),
      ),
      struct_serializer_.field_spec_to_field_adapter(
        name: "limit",
        number: 1,
        doc: "",
        default: 0,
        type_sig: type_descriptor_.Primitive(type_descriptor_.Int32),
        get: fn(s: ListCatalogCardsRequest) { s.limit },
        set: fn(s: ListCatalogCardsRequest, v: Int) { ListCatalogCardsRequest(..s, limit: v) },
        serializer: struct_serializer_.Eager(limit_serializer),
      ),
    ],
    default: list_catalog_cards_request_default,
    get_unrecognized: fn(s) { s.unrecognized_ },
    set_unrecognized: fn(s, u) { ListCatalogCardsRequest(..s, unrecognized_: u) },
    removed_numbers: [],
    recognized_slot_count: 2,
    decode_dense_json: fn(arr, keep) {
      use #(offset, arr) <- result_.try(case arr {
        [] -> Ok(#(0, []))
        [elem, ..arr] -> decode_.run(elem, offset_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      use #(limit, arr) <- result_.try(case arr {
        [] -> Ok(#(0, []))
        [elem, ..arr] -> decode_.run(elem, limit_serializer.internal_adapter.decode_json(keep)) |> result_.map(fn(v) { #(v, arr) })
      })
      let unrecognized_ = struct_serializer_.make_unrecognized_fields_json(arr, list_.length(arr) + 2, keep)
      Ok(ListCatalogCardsRequest(offset:, limit:, unrecognized_:))
    },
    decode_binary: fn(bits, slots_to_fill, keep) {
      use #(offset, bits) <- result_.try(case slots_to_fill > 0 {
        active if active -> offset_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#(0, bits))
      })
      use #(limit, bits) <- result_.try(case slots_to_fill > 1 {
        active if active -> limit_serializer.internal_adapter.decode(bits, keep)
        _ -> Ok(#(0, bits))
      })
      Ok(#(ListCatalogCardsRequest(offset:, limit:, unrecognized_: struct_serializer_.None), bits))
    },
  )
}

// ==============================================================================
// method ListCatalogCards
// ==============================================================================

pub fn list_catalog_cards_method() -> method_.Method(ListCatalogCardsRequest, CatalogCardList) {
  method_.Method(
    name: "ListCatalogCards",
    number: 102,
    doc: "",
    request_serializer: list_catalog_cards_request_serializer(),
    response_serializer: catalog_card_list_serializer(),
  )
}
