//  ______                        _               _  _  _
//  |  _  \                      | |             | |(_)| |
//  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_
//  | | | | / _ \  | '_ \  / _ \ | __|  / _ \ / _` || || __|
//  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_
//  |___/   \___/  |_| |_| \___/  \__|  \___| \__,_||_| \__|
//
// Generated by skir-typescript-gen
// Home: https://github.com/gepheum/skir-typescript-gen
//
// To install the Skir client library:
//   npm i skir-client

import * as $ from "skir-client";

// -----------------------------------------------------------------------------
// struct RefreshCatalogRequest
// -----------------------------------------------------------------------------

/** Deeply immutable. If you need mutability, use `RefreshCatalogRequest.Mutable`. */
export declare class RefreshCatalogRequest extends $._FrozenBase {
  /**
   * Creates a new instance of `RefreshCatalogRequest`.
   *
   * You must specify all the fields unless you use `create<"partial">({...})>`,
   * in which case missing fields are set to their default values.
   */
  static create<_Wholeness extends "whole" | "partial" = "whole">(
    initializer: RefreshCatalogRequest.Initializer<_Wholeness>,
  ): RefreshCatalogRequest;

  private constructor();

  readonly unit: boolean;

  /** Returns this instance (no-op). */
  toFrozen(): this;

  /** Returns a mutable shallow copy of this instance. */
  toMutable(): RefreshCatalogRequest.Mutable;

  /** Default instance with all fields set to their default values. */
  static readonly DEFAULT: RefreshCatalogRequest;

  /** Serializer for `RefreshCatalogRequest` instances. */
  static readonly serializer: $.Serializer<RefreshCatalogRequest>;

  /** Mutable version of this class. */
  static readonly Mutable: typeof RefreshCatalogRequest_Mutable;

  readonly [$._INITIALIZER]: RefreshCatalogRequest.Initializer | undefined;
  private readonly FROZEN: undefined;
}

/**
 * Mutable version of `RefreshCatalogRequest`.
 *
 * @alias RefreshCatalogRequest.Mutable
 */
declare class RefreshCatalogRequest_Mutable {
  /**
   * Creates a new mutable instance.
   *
   * Fields not specified in `initializer` will be set to their default values.
   */
  constructor(initializer?: RefreshCatalogRequest.Initializer<"partial">);

  unit: boolean;

  /** Returns a deeply-immutable copy of this instance. */
  toFrozen(): RefreshCatalogRequest;

  readonly [$._INITIALIZER]: RefreshCatalogRequest.Initializer | undefined;
}

export declare namespace RefreshCatalogRequest {
  interface _Initializer<_Wholeness extends "whole" | "partial"> {
    readonly unit: boolean;
  }

  export type Initializer<_Wholeness extends "whole" | "partial" = "whole"> =
    _Wholeness extends "whole" ? _Initializer<"whole"> : Partial<_Initializer<"partial">>;

  /** Mutable version of RefreshCatalogRequest. */
  export type Mutable = RefreshCatalogRequest_Mutable;
  export type OrMutable = RefreshCatalogRequest | Mutable;
}

// -----------------------------------------------------------------------------
// enum RefreshCatalogResponse
// -----------------------------------------------------------------------------

/** Deeply immutable. */
export declare class RefreshCatalogResponse extends $._EnumBase {
  /**
   * Constant indicating an unknown `RefreshCatalogResponse` (kind: '?').
   *
   * Default value for fields of type `RefreshCatalogResponse`.
   */
  static readonly UNKNOWN: RefreshCatalogResponse;
  static readonly SUCCESS: RefreshCatalogResponse;
  static readonly ERROR: RefreshCatalogResponse;

  /** Gets or creates a `RefreshCatalogResponse` instance from the given initializer. */
  static create<_Wholeness extends "whole" | "partial" = "whole">(
    initializer: RefreshCatalogResponse.Initializer<_Wholeness>,
  ): RefreshCatalogResponse;

  /**
   * This instance as the union of all the variant types.
   *
   * Use `union.kind` to determine the variant held by this instance.
   */
  declare readonly union: RefreshCatalogResponse.UnionView;

  /** Serializer for `RefreshCatalogResponse` instances. */
  static readonly serializer: $.Serializer<RefreshCatalogResponse>;
}

export declare namespace RefreshCatalogResponse {
  /** Identifies a variant. */
  export type Kind = "UNKNOWN" | "SUCCESS" | "ERROR";

  export type Initializer<_Wholeness extends "whole" | "partial" = "whole"> =
    | RefreshCatalogResponse
    | "UNKNOWN"
    | "SUCCESS"
    | "ERROR";

  /** View of a `RefreshCatalogResponse` as a union type. */
  export type UnionView =
    | { kind: "UNKNOWN"; value: undefined }
    | { kind: "SUCCESS"; value: undefined }
    | { kind: "ERROR"; value: undefined };
}

// -----------------------------------------------------------------------------
// Methods
// -----------------------------------------------------------------------------

export const RefreshCatalog: $.Method<RefreshCatalogRequest, RefreshCatalogResponse>;
