//  ______                        _               _  _  _
//  |  _  \                      | |             | |(_)| |
//  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_
//  | | | | / _ \  | '_ \  / _ \ | __|  / _ \ / _` || || __|
//  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_
//  |___/   \___/  |_| |_| \___/  \__|  \___| \__,_||_| \__|
//
// Generated by skir-typescript-gen
// Home: https://github.com/gepheum/skir-typescript-gen
//
// To install the Skir client library:
//   npm i skir-client

import * as $ from "skir-client";

// -----------------------------------------------------------------------------
// struct CatalogCard
// -----------------------------------------------------------------------------

/** Deeply immutable. If you need mutability, use `CatalogCard.Mutable`. */
export declare class CatalogCard extends $._FrozenBase {
  /**
   * Creates a new instance of `CatalogCard`.
   *
   * You must specify all the fields unless you use `create<"partial">({...})>`,
   * in which case missing fields are set to their default values.
   */
  static create<_Wholeness extends "whole" | "partial" = "whole">(
    initializer: CatalogCard.Initializer<_Wholeness>
  ): CatalogCard;

  private constructor();

  readonly id: string;
  readonly name: string;
  readonly setCode: string;

  /** Returns this instance (no-op). */
  toFrozen(): this;

  /** Returns a mutable shallow copy of this instance. */
  toMutable(): CatalogCard.Mutable;

  /** Default instance with all fields set to their default values. */
  static readonly DEFAULT: CatalogCard;

  /** Serializer for `CatalogCard` instances. */
  static readonly serializer: $.Serializer<CatalogCard>;

  /** Mutable version of this class. */
  static readonly Mutable: typeof CatalogCard_Mutable;

  readonly [$._INITIALIZER]: CatalogCard.Initializer | undefined;
  private readonly FROZEN: undefined;
}

/**
 * Mutable version of `CatalogCard`.
 *
 * @alias CatalogCard.Mutable
 */
declare class CatalogCard_Mutable {
  /**
   * Creates a new mutable instance.
   *
   * Fields not specified in `initializer` will be set to their default values.
   */
  constructor(initializer?: CatalogCard.Initializer<"partial">);

  id: string;
  name: string;
  setCode: string;

  /** Returns a deeply-immutable copy of this instance. */
  toFrozen(): CatalogCard;

  readonly [$._INITIALIZER]: CatalogCard.Initializer | undefined;
}

export declare namespace CatalogCard {
  interface _Initializer<_Wholeness extends "whole" | "partial"> {
    readonly id: string;
    readonly name: string;
    readonly setCode: string;
  }

  export type Initializer<_Wholeness extends "whole" | "partial" = "whole"> =
    _Wholeness extends "whole" ? _Initializer<"whole"> : Partial<_Initializer<"partial">>;

  /** Mutable version of CatalogCard. */
  export type Mutable = CatalogCard_Mutable;
  export type OrMutable = CatalogCard | Mutable;
}

// -----------------------------------------------------------------------------
// struct CatalogCardList
// -----------------------------------------------------------------------------

/** Deeply immutable. If you need mutability, use `CatalogCardList.Mutable`. */
export declare class CatalogCardList extends $._FrozenBase {
  /**
   * Creates a new instance of `CatalogCardList`.
   *
   * You must specify all the fields unless you use `create<"partial">({...})>`,
   * in which case missing fields are set to their default values.
   */
  static create<_Wholeness extends "whole" | "partial" = "whole">(
    initializer: CatalogCardList.Initializer<_Wholeness>
  ): CatalogCardList;

  private constructor();

  readonly data: ReadonlyArray<CatalogCard>;
  readonly total: number;
  readonly offset: number;
  readonly limit: number;

  /** Returns this instance (no-op). */
  toFrozen(): this;

  /** Returns a mutable shallow copy of this instance. */
  toMutable(): CatalogCardList.Mutable;

  /** Default instance with all fields set to their default values. */
  static readonly DEFAULT: CatalogCardList;

  /** Serializer for `CatalogCardList` instances. */
  static readonly serializer: $.Serializer<CatalogCardList>;

  /** Mutable version of this class. */
  static readonly Mutable: typeof CatalogCardList_Mutable;

  readonly [$._INITIALIZER]: CatalogCardList.Initializer | undefined;
  private readonly FROZEN: undefined;
}

/**
 * Mutable version of `CatalogCardList`.
 *
 * @alias CatalogCardList.Mutable
 */
declare class CatalogCardList_Mutable {
  /**
   * Creates a new mutable instance.
   *
   * Fields not specified in `initializer` will be set to their default values.
   */
  constructor(initializer?: CatalogCardList.Initializer<"partial">);

  data: ReadonlyArray<CatalogCard.OrMutable>;
  total: number;
  offset: number;
  limit: number;

  /**
   * If the value of `data` is already mutable, returns it as-is.
   * Otherwise, makes a mutable copy, assigns it back to `data` and returns it.
   */
  get mutableData(): Array<CatalogCard.OrMutable>;

  /** Returns a deeply-immutable copy of this instance. */
  toFrozen(): CatalogCardList;

  readonly [$._INITIALIZER]: CatalogCardList.Initializer | undefined;
}

export declare namespace CatalogCardList {
  interface _Initializer<_Wholeness extends "whole" | "partial"> {
    readonly data: ReadonlyArray<CatalogCard.Initializer<_Wholeness>>;
    readonly total: number;
    readonly offset: number;
    readonly limit: number;
  }

  export type Initializer<_Wholeness extends "whole" | "partial" = "whole"> =
    _Wholeness extends "whole" ? _Initializer<"whole"> : Partial<_Initializer<"partial">>;

  /** Mutable version of CatalogCardList. */
  export type Mutable = CatalogCardList_Mutable;
  export type OrMutable = CatalogCardList | Mutable;
}

// -----------------------------------------------------------------------------
// struct ListCatalogCardsRequest
// -----------------------------------------------------------------------------

/** Deeply immutable. If you need mutability, use `ListCatalogCardsRequest.Mutable`. */
export declare class ListCatalogCardsRequest extends $._FrozenBase {
  /**
   * Creates a new instance of `ListCatalogCardsRequest`.
   *
   * You must specify all the fields unless you use `create<"partial">({...})>`,
   * in which case missing fields are set to their default values.
   */
  static create<_Wholeness extends "whole" | "partial" = "whole">(
    initializer: ListCatalogCardsRequest.Initializer<_Wholeness>
  ): ListCatalogCardsRequest;

  private constructor();

  readonly offset: number;
  readonly limit: number;

  /** Returns this instance (no-op). */
  toFrozen(): this;

  /** Returns a mutable shallow copy of this instance. */
  toMutable(): ListCatalogCardsRequest.Mutable;

  /** Default instance with all fields set to their default values. */
  static readonly DEFAULT: ListCatalogCardsRequest;

  /** Serializer for `ListCatalogCardsRequest` instances. */
  static readonly serializer: $.Serializer<ListCatalogCardsRequest>;

  /** Mutable version of this class. */
  static readonly Mutable: typeof ListCatalogCardsRequest_Mutable;

  readonly [$._INITIALIZER]: ListCatalogCardsRequest.Initializer | undefined;
  private readonly FROZEN: undefined;
}

/**
 * Mutable version of `ListCatalogCardsRequest`.
 *
 * @alias ListCatalogCardsRequest.Mutable
 */
declare class ListCatalogCardsRequest_Mutable {
  /**
   * Creates a new mutable instance.
   *
   * Fields not specified in `initializer` will be set to their default values.
   */
  constructor(initializer?: ListCatalogCardsRequest.Initializer<"partial">);

  offset: number;
  limit: number;

  /** Returns a deeply-immutable copy of this instance. */
  toFrozen(): ListCatalogCardsRequest;

  readonly [$._INITIALIZER]: ListCatalogCardsRequest.Initializer | undefined;
}

export declare namespace ListCatalogCardsRequest {
  interface _Initializer<_Wholeness extends "whole" | "partial"> {
    readonly offset: number;
    readonly limit: number;
  }

  export type Initializer<_Wholeness extends "whole" | "partial" = "whole"> =
    _Wholeness extends "whole" ? _Initializer<"whole"> : Partial<_Initializer<"partial">>;

  /** Mutable version of ListCatalogCardsRequest. */
  export type Mutable = ListCatalogCardsRequest_Mutable;
  export type OrMutable = ListCatalogCardsRequest | Mutable;
}

// -----------------------------------------------------------------------------
// Methods
// -----------------------------------------------------------------------------

export const ListCatalogCards: $.Method<ListCatalogCardsRequest, CatalogCardList>;
